### ISSUE TITLE
[Feature Request] Can back to previous field

### ISSUE THREAD

**Issue by nguyenhuutinh** [adar2378/pin_code_fields#1]
Hi, can you support to back to previous field by back /delete button. thanks

**Comment by adar2378** [comment]
Hi, Sure I'll do that this weekend :) A good feature to have!

**Comment by adar2378** [comment]
I tried to add this, but it has a limitation! But still better than before. Will push the code soon

**Comment by adar2378** [comment]
Hi, I've changed the whole package for this feature. It was a bit tricky to solve the problem. But I've done it. Check the new version :)
