### ISSUE TITLE
bug: iOS autofill can not trigger ValueChanged function

### ISSUE THREAD

**Issue by glennWang** [adar2378/pin_code_fields#10]
In my use case, if the pin codes positions have been filled fully. Then the codes will be commited automatically.

Now，IOS autofill can not trigger ValueChanged function, so I don't not know  when the pin code has been filled.

`final ValueChanged<String> currentText`

**Comment by adar2378** [comment]
I'll check soon

**Comment by adar2378** [comment]
I've pushed an update. Could you check and let me know if it's working. Thanks

**Comment by glennWang** [comment]
The  update is working.  😀

Thank you very much !
