### ISSUE TITLE
Cannot tap while running integration tests

### ISSUE THREAD

**Issue by istriman29022020** [adar2378/pin_code_fields#100]
I'm using it for a project and trying to write an integration on it. Following lines are used to enter the value in it.

`await driver.waitFor(otpTextField);
      await driver.tap(otpTextField);
      await driver.enterText("1");`
**Expected**:
The field takes the tap and gets the text.
**Actual**
The flutter drive times out saying tap is taking too long. I can manually tap and enter values though.

Version: 5.0.1
Flutter Version: 1.20.1
Dart: 2.9.0

**Comment by adar2378** [comment]
Interesting problem. I'll look into it

**Comment by alextrujillo4** [comment]
is this bug fixed?

**Comment by alextrujillo4** [comment]
i also realized, this Widget blocks all other widgets in the same page (or screen) and it does not allows to find them by id or another attribute when doing integration testing (i needed to comment the widget to allow my testing).

**Comment by adar2378** [comment]
Thanks for your information. We did widget testing and it was working fine. Need to look into the integration test.

**Comment by ciceropablo** [comment]
Hi, @adar2378!
Any news about that?

**Comment by paladinze** [comment]
Maybe try this, it worked for me:
```
await driver.runUnsynchronized(() async {
	final pinField = find.descendant(
		of: find.byType('PinCodeTextField'),
		matching: find.byType('AnimatedContainer'),
		firstMatchOnly: true,
	);
	await driver.tap(pinField);
	await driver.enterText('123456');
});
```

- `runUnsynchronized` is needed to disable "frame sync", as the blinking cursor of the field cause animation on the entire screen to never settle, which in turn prevents tapping from executing (for example on a back button on the page)
- `tap` must hit on the center of the descendent to change individual field into focus state

**Comment by ciceropablo** [comment]
Thanks for the tips, @paladinze. I'll try.

**Comment by anuragarwalkar** [comment]
We are also facing the same issues will try the @paladinze approach and see if that works

**Comment by anuragarwalkar** [comment]
> We are also facing the same issues will try the @paladinze approach and see if that works

Thanks @paladinze adding value by type works for now
