### ISSUE TITLE
RootNavigator issue

### ISSUE THREAD

**Issue by theweiweiway** [adar2378/pin_code_fields#101]
Hi, I was following issue #64 and i saw the newest 5.0.1 update which adds 
```useRootNavigator: true```

However, I am still getting the root navigator bug. The only way I can fix this, is if I change 4 
```Navigator.pop()```
to
```Navigator.of(context, rootNavigator: true).pop();```

Besides this, the package is awesome - Thanks!

**Comment by adar2378** [comment]
Alright, thanks! I'll try to change this part of the code
