### ISSUE TITLE
Holding delete button on keyboard only clears the last digit/input, not all digits/inputs

### ISSUE THREAD

**Issue by mdjabeer4u** [adar2378/pin_code_fields#11]
when entering the input and you are halfway through, say you are in 5th input out of 6, and you hold the delete button to clear all fields, it only delete the last inputted field and cursor goes back to starting field without clearing out all the fields.

**Comment by adar2378** [comment]
I'm a little busy with other works. I will try to see what I can do about this bug after 2 days I think. Thanks for pointing it out 😃

**Comment by adar2378** [comment]
Does this happen only on iOS?

**Comment by mdjabeer4u** [comment]
I have resolved this bug. just add the extra condition at the end of **_textEditingController.addListener** in **initState** method as follows :
`    if (value.length == 0) {
          setState(() {
            _inputList.fillRange(0, widget.length, "");
          });
        }`

**Comment by adar2378** [comment]
Thank you so much. I tried on a android device it didn't happen. I'll check again on iOS and update the code.
