### ISSUE TITLE
Unable to position entered text as desired

### ISSUE THREAD

**Issue by robertflesch** [adar2378/pin_code_fields#113]
Love the library!
I looked through the code, and I dont see any flexibility on how the entered data is positioned relative to the underlines.
The values are hovering way above the lines.
I would like the 0's closer to the lines below them. 
<img width="329" alt="SIGNUP_SCREEN_2_PNG" src="https://user-images.githubusercontent.com/1186354/95905509-f600b980-0d66-11eb-9747-6ccb8bde00f1.png">

This is what I was given by designer.
<img width="329" alt="SIGNUP_SCREEN_2_PNG" src="https://user-images.githubusercontent.com/1186354/95905879-614a8b80-0d67-11eb-90f2-48e98c54b4cb.png">

Also default background values would be handy.

Code to generate my PinCodeField is
PinCodeTextField(
	appContext: context,
	length: 6,
	backgroundColor: Colors.transparent,
	controller: textEditingController,
	keyboardType: TextInputType.number,
	pinTheme: PinTheme(
	  fieldHeight: 40,
	  fieldWidth: 20,
	  activeColor: Constants.greenNew,
	),
)

Any thoughts on how I can lower the entered values?

**Comment by adar2378** [comment]
Could you try a smaller fieldHeight and see if it solves the problem?

**Comment by robertflesch** [comment]
> Could you try a smaller fieldHeight and see if it solves the problem?

Doh, that fixed it perfectly! 
Thanks for the quick response.

**Comment by adar2378** [comment]
Glad it helped, cheers!
