### ISSUE TITLE
Neumorphic support

### ISSUE THREAD

**Issue by subzero911** [adar2378/pin_code_fields#115]
I use https://pub.dev/packages/flutter_neumorphic style in my application.
I want to wrap every pin cell into Neumorphic container. Is it possible?

**Comment by adar2378** [comment]
I'm afraid you can't use that package. But you can use different shadows to make the pin fields look like  them I think

**Comment by subzero911** [comment]
No, BoxShadows are not look like Neumorphic.
Could you provide an option to use a custom widget as a cell?

**Comment by adar2378** [comment]
Neumorphic design is just shadows mostly. You gotta use different color. If you research a bit I think you will find it how to use box shadows to make a container look like the neumorphic designs

**Comment by adar2378** [comment]
https://medium.com/flutter-community/neumorphic-designs-in-flutter-eab9a4de2059
You can follow this article
