### ISSUE TITLE
claer TextEditingController not working

### ISSUE THREAD

**Issue by zeczen** [adar2378/pin_code_fields#116]
my onChanged in PinCodeTextField

` 
onChanged: (String text) {
                  try {
                    int.parse(text);
                  } catch(e) {
                    setState(() {
                      _textEditingController .clear();
                    codeFromSMS = text;
                    });
                    return;
                  }
                  setState(() {
                    codeFromSMS = text;
                  });
 }
`
When I try to clear the textEditingController when the user enters an invalid input, it does not clear and the added input order is confused

**Comment by adar2378** [comment]
Could you try with int.tryParse() instead of int.parse and let me know if you're still facing the same issue.

**Comment by zeczen** [comment]
It still does not work, the problem is with the TextEditingController not with the catch-try structure

**Comment by adar2378** [comment]
Thanks, I will look into it today

**Comment by adar2378** [comment]
I don't exactly know why it's not working properly. Maybe because two different listeners is trying to modify at the very same time. Anyway, I found a hack which is working. 
`await Future.delayed(Duration(milliseconds: 100));
                        textEditingController.clear();`

try this.

**Comment by zeczen** [comment]
YAY! it works, impressive.

**Comment by adar2378** [comment]
Glad it worked. Closing this now.

**Comment by Techno-Disaster** [comment]
Hey @adar2378, thanks for the great package but can we reopen this and work on a fix too ? Thanks :D

**Comment by Techno-Disaster** [comment]
setting the text before firing onChanged fixed it https://github.com/adar2378/pin_code_fields/compare/master...Techno-Disaster:pin_code_fields:master#diff-83dbd65b3cced53d0eca96d4765e9531f0d73944459a12472c24ff3a5d68411eR481
