### ISSUE TITLE
Version 6.0.0 breaks Flutter tests

### ISSUE THREAD

**Issue by tudor07** [adar2378/pin_code_fields#119]
I use this library in a few of my screens, for which I use `flutter_test` to do some widget testing.
After upgrading to version `6.0.0`, everytime my test gets to a screen that uses `PinCodeTextField` I get the following error:
```
pumpAndSettle timed out
```

I think this usually means that some animations/frames are not finishing or something.
After I downgraded back to `5.2.0` my tests pass.

**Comment by adar2378** [comment]
In 6.0.0 I added cursor support, which keeps on blinking all the time. If this animation is blocking the test then you can set `showCursor = false`

Besides, see this answer, if it helps : https://stackoverflow.com/questions/52176777/how-to-wait-for-a-future-to-complete-in-flutter-widget-test

**Comment by adar2378** [comment]
Please update to 6.0.1 before testing it with `showCursor = false`
