### ISSUE TITLE
Getting error like 'dart:ui/painting.dart': Failed assertion: line 1147: '<optimized out>': is not true.

### ISSUE THREAD

**Issue by sureace** [adar2378/pin_code_fields#120]
When i migrate to latest version, i getting this error continuously in the logs like infinite. Below is my code.
 `PinCodeTextField(
                                                    appContext: context,
                                                    length: 6,
                                                    pinTheme: PinTheme(
                                                      shape: PinCodeFieldShape.box,
                                                      borderRadius: BorderRadius.circular(10),
                                                      borderWidth: 1,
                                                      fieldWidth: SizeConfig.widthMultiplier * 12,
                                                      fieldHeight: SizeConfig.widthMultiplier * 12,
                                                      activeColor: Colors.black87,
                                                      selectedColor: AppTheme.btnGreen,
                                                      inactiveColor: Colors.grey[300],
                                                    ),
                                                    textStyle: TextStyle(fontSize: 14,fontWeight: FontWeight.normal),
                                                    onChanged: (value){
                                                      print(value);
                                                      setState(() {
                                                        smsPinEntered = false;
                                                        smsPin = value;
                                                      });
                                                    },
                                                    onCompleted: (status){
                                                      print("Completed :$status");
                                                      setState(() {
                                                        smsPinEntered = true;
                                                      });
                                                    },
                                                    beforeTextPaste: (text) {
                                                      print("Allowing to paste $text");
                                                      //if you return true then it will show the paste confirmation dialog. Otherwise if false, then nothing will happen.
                                                      //but you can show anything you want here, like your pop up saying wrong paste format or etc
                                                      return true;
                                                    }
                                                )`

**Comment by adar2378** [comment]
Hi could you show your flutter doctor info. Which flutter channel and version you're using.

**Comment by sureace** [comment]
Hi thanks for prompt response. Error has gone after change the code with below.

PinCodeTextField(
                                                    appContext: context,
                                                    length: 6,
                                                    obscureText: false,
                                                    obscuringCharacter: '*',
                                                    animationType: AnimationType.fade,
                                                    cursorColor: Colors.black,
                                                    animationDuration: Duration(milliseconds: 300),
                                                    backgroundColor: Colors.transparent,
                                                    enableActiveFill: true,
                                                    controller: pinController,
                                                    keyboardType: TextInputType.number,
                                                    pinTheme: PinTheme(
                                                      shape: PinCodeFieldShape.box,
                                                      borderRadius: BorderRadius.circular(10),
                                                      borderWidth: 1,
                                                      activeFillColor: Colors.white,
                                                      inactiveFillColor: Colors.grey[100],
                                                      selectedFillColor: Colors.white,
                                                      fieldWidth: SizeConfig.widthMultiplier * 12,
                                                      fieldHeight: SizeConfig.widthMultiplier * 12,
                                                      activeColor: Colors.black87,
                                                      selectedColor: AppTheme.btnGreen,
                                                      inactiveColor: Colors.grey[300],
                                                    ),
                                                    textStyle: TextStyle(fontSize: 14,fontWeight: FontWeight.normal),
                                                    onChanged: (value){
                                                      print(value);
                                                      setState(() {
                                                        smsPinEntered = false;
                                                        smsPin = value;
                                                      });
                                                    },
                                                    onCompleted: (status){
                                                      print("Completed :$status");
                                                      setState(() {
                                                        smsPinEntered = true;
                                                      });
                                                    },
                                                    beforeTextPaste: (text) {
                                                      print("Allowing to paste $text");
                                                      //if you return true then it will show the paste confirmation dialog. Otherwise if false, then nothing will happen.
                                                      //but you can show anything you want here, like your pop up saying wrong paste format or etc
                                                      return true;
                                                    }
                                                )

Flutter doctor
----------------
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.4 19E287, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.5)

**Comment by adar2378** [comment]
Glad to hear it. Which change solved the error?

**Comment by wwwhttpru** [comment]
Solution to the problem.
`cursorColor: Colors.black.`

**Comment by Tmarks2** [comment]
Changing 
cursorColor: Colors.black Fixed The Problem for me as Well! Thank you @wwwhttpru

**Comment by darkang3lz92** [comment]
Caused by `Theme.textSelectionTheme.cursorColor` null value (Probably from flutter recent update?). Is this better if we assign default `cursorColor` as `Theme.accentColor` if `Theme.textSelectionTheme.cursorColor` is null?

**Comment by adar2378** [comment]
Yeah sounds like a good idea! The recent update looks a bit inconsistent which is causing this error.
