### ISSUE TITLE
Not working on the latest version of the Flutter

### ISSUE THREAD

**Issue by mrazaimtiaz** [adar2378/pin_code_fields#121]
I got the fallowing message during installation.
it required the flutter version smaller or equal than 2.0.0
pub get failed (1; Because 'flutter_application_name' depends on pin_code_fields >=5.0.0 which requires Flutter SDK version >=1.20.0 <2.0.0, version solving failed.)

**Comment by mrazaimtiaz** [comment]
instead of   "pin_code_fields: ^6.0.1" in pubspec.yaml, I used "pin_code_fields: " without version number its working now

**Comment by adar2378** [comment]
Because the version 6.0.1 requires you to have Flutter version 1.2.0 installed at least.

When you use `"pin_code_fields":` it finds the suitable version of this package which is compatible and installs that version of that package, which should be 4.x.x

**Comment by mrazaimtiaz** [comment]
Thanks @adar2378  for your help. Much appreciated
