### ISSUE TITLE
Issue with focus on another text field. 

### ISSUE THREAD

**Issue by devons-mum** [adar2378/pin_code_fields#122]
Hi Adar

Great library, just found a bug not sure if it's been mentioned before. I've shared a screen recording that will hopefully help. 

Id struggle to explain it but basically when you show hide the field it's almost like it's grabing the focus or something, and disabling the keyboard when returning to another input.

Note: this only seems to happen on an actual device, android and ios.

https://drive.google.com/file/d/1PV5bdU2UCkfLvF5HcBkVUmRwjmojObBO/view?usp=sharing
Thanks, Devon

**Comment by adar2378** [comment]
Hi, thanks for the feedback. I will try to investigate it

**Comment by trung39** [comment]
Hi @adar2378 ,

I'm also facing this issue and not by showing or hiding the field, but by navigating to a page containing pin code field. When I back to the previous page, the delete key is not working until, and if I press another key, it replace the current text by that word.
And my issue reproduced only on iOS.

I'm using the latest version of your example in the clip to reproduce this, please have a look.
https://user-images.githubusercontent.com/25921836/179478964-01658c07-f674-426a-a05f-ff51da9fd95c.mp4

Hope there is a solution for this.
Thank you.
