### ISSUE TITLE
textCapitalization property is not honored

### ISSUE THREAD

**Issue by tudor07** [adar2378/pin_code_fields#123]
`textCapitalization` property is not honored.

1. Set `textCapitalization` to `TextCapitalization.characters` on a `PinCodeTextField`
2. Open the keyboard

Expected: all characters are uppercase on the keyboard
Actual: characters are lowercase on the keyboard

**Comment by tudor07** [comment]
Update:
If I add: `keyboardType: TextInputType.text` seems to work 🤷‍♂️

**Comment by adar2378** [comment]
Yes it only supports text type keyboard.
