### ISSUE TITLE
'dart:ui/painting.dart': Failed assertion: line 1147: '<optimized out>': is not true.

### ISSUE THREAD

**Issue by muhamadkhuram** [adar2378/pin_code_fields#128]
'dart:ui/painting.dart': Failed assertion: line 1147: '<optimized out>': is not true.
continuously about 10 times in a second appearing whenever I tap this widget... 
Note: I didn't change anything.. in the field.

**Comment by tekno0ryder** [comment]
I have same error too

`
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during paint():
'dart:ui/painting.dart': Failed assertion: line 1147: '<optimized out>': is not true.

The relevant error-causing widget was
PinCodeTextField
lib\…\home\login.dart:138
When the exception was thrown, this was the stack
#2      Paint.color= (dart:ui/painting.dart:1147:12)
#3      CursorPainter.paint
package:pin_code_fields/src/cursor_painter.dart:14
#4      RenderCustomPaint._paintWithPainter
package:flutter/…/rendering/custom_paint.dart:531
#5      RenderCustomPaint.paint
package:flutter/…/rendering/custom_paint.dart:572
#6      RenderObject._paintWithContext
package:flutter/…/rendering/object.dart:2311
...
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#2006d relayoutBoundary=up5
RenderObject: RenderCustomPaint#2006d relayoutBoundary=up5
    parentData: <none> (can use size)
    constraints: BoxConstraints(0.0<=w<=40.0, 0.0<=h<=48.0)
    size: Size(0.0, 28.0)
`

**Comment by adar2378** [comment]
Please see the pinned issue : https://github.com/adar2378/pin_code_fields/issues/120

Basically, you will have to provide the cursor color
