### ISSUE TITLE
Hide underline after filling password field.

### ISSUE THREAD

**Issue by Prn-Ice** [adar2378/pin_code_fields#132]
Is it possible to hide the underline when a pin has been entered?

**Comment by adar2378** [comment]
Not exactly, but there is a hack. Which is simply set the `activeColor` same as the background so they will blend together and the border won't be shown.

**Comment by Prn-Ice** [comment]
Noice, I'll do that.

**Comment by Prn-Ice** [comment]
This works if I wanted to hide the underline after filling the field. I want to hide the underline on each input box as values are entered like in this image.
![image](https://user-images.githubusercontent.com/48252841/102692535-41768e80-4214-11eb-974a-9d1e1872c794.png)
I don't think it's currently possible.

**Comment by Prn-Ice** [comment]
It is, just change the `activeColor` to background color
