### ISSUE TITLE
Box entries flicker and move down and up constantly

### ISSUE THREAD

**Issue by olivierbrand** [adar2378/pin_code_fields#134]
Have tried the plugin, great amount of customization. However I am faced with an issue I cannot resolve, the boxes flicker and move down and up again constantly
I have noticed that this happens when: shape: PinCodeFieldShape.box, is set. However, it has to be set otherwise we cannot enter anything

Our code is:

PinCodeTextField(
                controller: _controller,
                appContext: context,
                length: 4,
                onChanged: (value) => setState(() => _otpValue = value),
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                onCompleted: (value) => _submitForm(),
                keyboardType: TextInputType.number,
                inputFormatters: [
                  FilteringTextInputFormatter.allow(RegExp(r'\d'))
                ],
                pinTheme: PinTheme.defaults(
                  borderRadius: BorderRadius.circular(5),
                  shape: PinCodeFieldShape.box,
                  selectedFillColor: AppColors.white,
                  activeFillColor: AppColors.white,
                  inactiveColor: AppColors.white,
                  inactiveFillColor: AppColors.white,
                  selectedColor: AppColors.green,
                  activeColor: AppColors.white,
                ),
                autoDismissKeyboard: false,
                autoDisposeControllers: false,
                enableActiveFill: true,
                boxShadows: [
                  BoxShadow(
                    color: AppColors.black.withOpacity(0.2),
                    offset: Offset(0, 0),
                    blurRadius: 3,
                  )
                ],
              ),

See video attached

https://user-images.githubusercontent.com/37886981/102936641-c5738500-4465-11eb-95fd-590e2233c185.mov

**Comment by olivierbrand** [comment]
Issue was fixed on my side, we did not specify a cursor color. As this parameter is optional, we believe it is a bug in the library. Maybe by default assign cursorColor: Colors.transparent? Or figure out why the boxes flicker and translate back and forth

**Comment by adar2378** [comment]
It was fixed in 6.0.2, thanks for your feedback
