### ISSUE TITLE
Migrate to sound null safety

### ISSUE THREAD

**Issue by adarsh-technocrat** [adar2378/pin_code_fields#139]
### **Description**

- Migrate to sound null safety
- Bump up package version

**Comment by adar2378** [comment]
I've recently got an email from the dart team about null-safety migration. Soon I'll try it out.

**Comment by adarsh-technocrat** [comment]
Great @adar2378  if in some cases you are not working on this issue. I may land PR for this as it would be a great learning for me.

Thank you!

**Comment by adar2378** [comment]
Sure, go ahead :)

**Comment by adarsh-technocrat** [comment]
> Sure, go ahead :)

Thank you @adar2378  I'll land PR soon for this.
