### ISSUE TITLE
Pasting text issue with inputFormatters

### ISSUE THREAD

**Issue by EmmanuelVlad** [adar2378/pin_code_fields#14]
With the addition of `inputFormatters` when you paste an incorrect formatted text and then try to edit it, it'll reset the input.

**Example:**
Here I got `inputFormatters: [WhitelistingTextInputFormatter.digitsOnly]`
I can paste non digit text, but when I try to edit it, it resets
![](https://i.imgur.com/cNuRaxm.gif)

**Solution:**
Format the text when pasting it by using the `inputFormatters`

**Comment by adar2378** [comment]
Yeah, I think it is ok. This scenario will be very rare also.

**Comment by prasant10050** [comment]
Hey,I am facing the same issue,Give us to any solution
