### ISSUE TITLE
cursorHeight is null

### ISSUE THREAD

**Issue by jhionan** [adar2378/pin_code_fields#146]
`final cursorHeight = widget.cursorHeight ?? widget.textStyle.fontSize + 8;`

when you do not set the  `cursorHeight`  or  `textStyle.fontSize` + 8;

the constructor is calling textStyle.fontSize + 8 => what result in null + 8 

the result is a:
 
![image](https://user-images.githubusercontent.com/37809501/104626694-f31ea900-5674-11eb-8cec-8c4426ef2031.png)

Need to modify the fallback way of cursorHeight

**Comment by adar2378** [comment]
Hi, thanks for your feedback. We've worked on this and the next release version will contain the fix(within a couple of days). Meanwhile, you can directly use the master branch in your pubspec.

**Comment by jhionan** [comment]
Nice to know, I would create a PR for this after my work hours. But since its done, don't need to worry xD

I do appreciate your work here, this lib is very useful and very customizable. Thank you!

**Comment by jhionan** [comment]
> Hi, thanks for your feedback. We've worked on this and the next release version will contain the fix(within a couple of days). Meanwhile, you can directly use the master branch in your pubspec.

But I searched here about this issue and just saw about cursor color, not cursor height, if you are sure about this fix just close the issue here please.

**Comment by adar2378** [comment]
We have added fallback `TextStyle` which gets merged with the given `TextStyle`. So the `fontSize` won't be null. and we will add the assertion soon before releasing it so it can be better for developers to understand. Thanks for your warm words! <3

**Comment by adar2378** [comment]
This commit contains the changes, 6ddb593ca08c54c10e831d406414ca0546caf4f7 . Nevertheless, I'm always up to hear better solutions if we can do things in a better way.

**Comment by jhionan** [comment]
I like this solution, have a default TextStyle that can be overridden. xD
