### ISSUE TITLE
Focus selected color while using a custom keyboard

### ISSUE THREAD

**Issue by amorenew** [adar2378/pin_code_fields#151]
I have used a custom keyboard that requires a different FocusNode than the pin field
but I got an issue on selected color on your source code you have `_getColorFromIndex` function
which doesn't work with custom keyboard FocusNode because of this check `_focusNode.hasFocus`
 
 ```
   if (((_selectedIndex == index) ||
            (_selectedIndex == index + 1 && index + 1 == widget.length)) &&
        _focusNode.hasFocus) 
```
So I wonder is there any solution to add custom keyboard FocusNode as an option?

I am using custom keyboard from keyboard_actions package
<img width="393" alt="Screen Shot 2021-01-27 at 7 48 46 AM" src="https://user-images.githubusercontent.com/2842459/105948711-17ff1d00-6074-11eb-9a5a-c1808bb0696f.png">

<img width="445" alt="Screen Shot 2021-01-27 at 7 47 15 AM" src="https://user-images.githubusercontent.com/2842459/105948605-e1c19d80-6073-11eb-99eb-ff27c0cd98d8.png">

**Comment by adar2378** [comment]
The `FocusNode` that is being used in the `PinCodeTextField` is the one responsible. The other `FocusNode` should not create any problem here. Just make sure the `FocusNode` you're providing for `PinCodeTextField` has the focus.

**Comment by amorenew** [comment]
@adar2378 Unfortunately I cannot have a focus on PinCodeTextField and the custom keyboard at the same time.
So I wonder if I could get a second focus node as a parameter for my special case

**Comment by adar2378** [comment]
In that case, you can always modify the source code for your own need.

**Comment by amorenew** [comment]
I will close it for now until I got a PR
