### ISSUE TITLE
How Proper code for shape underline

### ISSUE THREAD

**Issue by echomartha** [adar2378/pin_code_fields#152]
```dart
pinTheme: PinTheme(
                            shape: PinCodeFieldShape.underline,
                            fieldHeight: 60,
                            fieldWidth: 50,
                            inactiveColor: kChacaYellowColor,
                            activeColor: kChacaYellowColor,
                            inactiveFillColor: kChacaYellowColor,
                            selectedColor: kChacaYellowColor,
                            selectedFillColor: kChacaYellowColor,
                            activeFillColor: hasError ? Colors.orange : Colors.white,
                          )
```

its showing eror like this

-  **A borderRadius can only be given for a uniform Border.**

**Comment by adar2378** [comment]
Looks like a bug, I'll fix it soon. Meanwhile, you can manually set the `borderRadus` to 0

**Comment by echomartha** [comment]
@adar2378  ok thanks for your response

**Comment by shubham-matale** [comment]
Is it solve? i am facing same issue after setting borderRadus to 0.

**Comment by PaoloGi** [comment]
same issue, .underline just not work

**Comment by mnomanmemon** [comment]
Facing same issue. Any update on this @adar2378 ?

**Comment by GitHelge** [comment]
This is oddly strange, now that I added a potential bugfix, the issue does not occur even without my previous changes.

**Comment by Anuj2799** [comment]
> same issue, .underline just not work

yeah, not working for me as well. Please solve this as soon as possible.
