### ISSUE TITLE
Unhandled Exception: setState() called after dispose()

### ISSUE THREAD

**Issue by andrea689** [adar2378/pin_code_fields#155]
if `blinkWhenObscuring` is `true` and fast change page after insert PIN, I have Exception at this lines: https://github.com/adar2378/pin_code_fields/blob/a3e33abb26dd91d6abbaa733b57b4a525660a32a/lib/src/pin_code_fields.dart#L444-L446

I think that `if (mounted)` solves the problem

**Comment by adar2378** [comment]
Ah, good catch! The next update will contain the fix! Thank you very much.

**Comment by nerotyc** [comment]
> Ah, good catch! The next update will contain the fix! Thank you very much.

@adar2378 Is this bug resolved now? I still encounter the same issue in version 7.3.0.

**Comment by IdemenB** [comment]
> > Ah, good catch! The next update will contain the fix! Thank you very much.
> 
> @adar2378 Is this bug resolved now? I still encounter the same issue in version 7.3.0.

I second this.
