### ISSUE TITLE
_textEditingController doesnt trigger the input

### ISSUE THREAD

**Issue by lexprimost** [adar2378/pin_code_fields#157]
Thanks for the package!
the doc says "controller" parameter is to control the text manually. i've added a textEditingcontroller and changing the controller text with a virtual keyboard. the number from the _textEditingController.text are printed in the console, but the package doesnt react to it. am i doing something wrong?

**Comment by lexprimost** [comment]
solved

**Comment by AyushBherwani1998** [comment]
@lexprimost what was the issue?
