### ISSUE TITLE
Hint/placeholder text is not available 

### ISSUE THREAD

**Issue by champ96k** [adar2378/pin_code_fields#161]
I want to achieve this type of design as shown in the below image

<img width="346" alt="Screenshot 2021-02-22 at 5 09 05 PM" src="https://user-images.githubusercontent.com/50237575/108703635-e3766800-7530-11eb-885d-b90d0a584f2f.png">

The hint or Placeholder text is not available in the exiting package, I am happy to contribute this amazing package 

#### Below are the possible way to solve this issue 
1. Add hint text in text field/Textform filed

**Comment by adar2378** [comment]
Sure, please go forward!

**Comment by champ96k** [comment]
@adar2378  Thanks for assigning me, I am currently working on that issue :)

**Comment by tanmoy27112000** [comment]
is this feature added?

**Comment by adrianFarkas** [comment]
I'm also interested in. This feature would be nice.

**Comment by champ96k** [comment]
@adrianFarkas  that's great to hear, unfortunately, I have not implemented it yet, you can go for it, I am happy to see this new feature.
