### ISSUE TITLE
using customize keyboard

### ISSUE THREAD

**Issue by CyrusChoi1984** [adar2378/pin_code_fields#169]
Thanks for contributor to share this library, it's really save me for many day to develop the same thing in Flutter.
For our original design, we would like to make the customize keyboard for input PIN, it's really help to protect if some devices is able to capture the key input from customer in OS level.

But when we using the package, we not able to do this.
attached the screen showing which overlap keyboard if I enable autofocus. Or even I click on the pincodetextfield it will trigger OS keyboard.

Any advice can sharing? Using default textfield readOnly = true is able to solve this issue, may I know you plan to bring readOnly to your package?
![螢幕截圖 2021-03-26 下午4 38 18](https://user-images.githubusercontent.com/10738380/112605841-b3352880-8e52-11eb-938e-b3002581256e.png)

**Comment by adar2378** [comment]
Hi, sure. I can expose readOnly. I am not sure about when because a bit busy with work. Maybe a couple of days.

**Comment by CyrusChoi1984** [comment]
Thanks!!!

**Comment by CyrusChoi1984** [comment]
Hi, @adar2378 may I know the status for this enhance?

**Comment by jijuthomas98** [comment]
hey i require this fix to, i dont want my app to trigger system keyboard, but to use custom keyboard.

**Comment by dhruvanbhalara** [comment]
@jijuthomas98 You can pass AlwaysDisabledFocusNode to hide the keyboard

`class AlwaysDisabledFocusNode extends FocusNode {
  @override
  bool get hasFocus => false;
}`
