### ISSUE TITLE
Change border color on error.

### ISSUE THREAD

**Issue by Prn-Ice** [adar2378/pin_code_fields#174]
Currently to change the border color to something like red when an error is induced, we have to create a boolean field to track the error state. Like in the example you used the field `hasError`. 

I was thinking, 
- add a field `errorBorderColor` to PinCodeField
- then when `errorController.add(ErrorAnimationType.shake)` is called
- Change the border color to `errorBorderColor`

I'll be happy to try working on this and submit a pull request.

**Comment by adar2378** [comment]
It sounds like a good approach. It would fantastic if you could implement it :)
