### ISSUE TITLE
onCompleted always hide keyboard

### ISSUE THREAD

**Issue by whysetiawan** [adar2378/pin_code_fields#175]
I want submit via onSubmitted. But onCompleted function always hide the keyboard. How can i fix the behaviour?

**Comment by adar2378** [comment]
Set `autoDismissKeyboard = false` when using the widget, then the keyboard won't be dismissed.

**Comment by whysetiawan** [comment]
> Set `autoDismissKeyboard = false` when using the widget, then the keyboard won't be dismissed.

Thanks
