### ISSUE TITLE
Publish new version to the pub.dev with the input field padding feature

### ISSUE THREAD

**Issue by gocal** [adar2378/pin_code_fields#177]
I've noticed that [recently](https://github.com/adar2378/pin_code_fields/commit/d069565d6c4b4393b293d33b1456edc0595b9027) input field padding has been added to the master branch however it has not been published to the pub.dev so I need to manually point to the repository branch in my pubspec.yaml

**Comment by adar2378** [comment]
Sorry for being a bit inactive lately. Busy with other works. I just pushed an update in pub.dev with the latest master, cheers.
