### ISSUE TITLE
CustomPaint problem

### ISSUE THREAD

**Issue by c0c4i** [adar2378/pin_code_fields#179]
I have problem with this widget, I have this "container" and I don't know why
```dart
PinCodeTextField(
  appContext: context,
  length: 5,
  animationType: AnimationType.fade,
  pinTheme: PinTheme(
    shape: PinCodeFieldShape.box,
    borderRadius: BorderRadius.circular(100),
    fieldWidth: 50,
    fieldHeight: 50,
    borderWidth: 2,
    activeFillColor: Colors.white,
    inactiveFillColor: Colors.white,
    selectedFillColor: Colors.white,
    activeColor: hasError ? Colors.red : Colors.blue,
    inactiveColor: EvaColors.grey800,
    selectedColor: EvaColors.grey800,
  ),
  cursorColor: Colors.black,
  animationDuration: Duration(milliseconds: 300),
  errorAnimationController: errorController,
  controller: textEditingController,
  keyboardType: TextInputType.number,
),
```
This is the code I used, any idea on why I see this? I also add photo
![Simulator Screen Shot - iPhone 12 Pro - 2021-05-10 at 11 20 54](https://user-images.githubusercontent.com/45185144/117637498-23d5a180-b182-11eb-81a2-1f32254abe9f.png)
![Simulator Screen Shot - iPhone 12 Pro - 2021-05-10 at 11 20 12](https://user-images.githubusercontent.com/45185144/117637509-2506ce80-b182-11eb-864e-3c845b8808f5.png)

**Comment by adar2378** [comment]
Please use `backgroundColor = Colors.white` to set the background color.
