### ISSUE TITLE
keyboard does not show on Flutter Channel beta, v1.11.0

### ISSUE THREAD

**Issue by MichaelSowah** [adar2378/pin_code_fields#18]
keyboard does not show on Flutter Channel beta, v1.11.0 even on tap.

**Comment by adar2378** [comment]
Is this happening in the example code?
Have you tried to switch flutter channel to stable see if it is working properly or not? 
It'll be really helpful if you could do that and share your experience.

**Comment by MichaelSowah** [comment]
it works well only on stable, but all my other text fields in all the channels work

**Comment by adar2378** [comment]
I wonder which API they've changed. I'll try to look out for it. Thanks for your issue submission.

**Comment by MichaelSowah** [comment]
I also have one of my testers complaining on stable channel

**Comment by adar2378** [comment]
Could you please give me the code that is not working?

**Comment by MichaelSowah** [comment]
this is the code, after testing for a while, I noticed that it works sometimes and sometimes not on the stable channel. when you touch the code field it doesn't bring out the keyboard.

PinCodeTextField(
                length: 4,
                obsecureText: false,
                animationType: AnimationType.scale,
                shape: PinCodeFieldShape.circle,
                animationDuration: Duration(milliseconds: 300),
                activeColor: Colors.black26,
                fieldHeight: 70,
                fieldWidth: 70,
                currentText: (value) {},
                textInputType: TextInputType.number,
                autoFocus: true,
              ),

**Comment by adar2378** [comment]
Looks like you're using the old version. This problem existed before in older versions. Could you please update to the newest version and try again and see if this is still happening?

**Comment by adar2378** [comment]
Duplicate of #4

**Comment by MichaelSowah** [comment]
ok, let me try and get back

**Comment by MichaelSowah** [comment]
working now on beta so far...thanks, will let you know if anything else comes up
