### ISSUE TITLE
append text programatically

### ISSUE THREAD

**Issue by MichaelSowah** [adar2378/pin_code_fields#19]
if I want to set a value in pin code fields how do I do that, I don't see any parameter that allows me set the text. you don't expose the textediting controller

**Comment by adar2378** [comment]
Yes, I've been working on it. But there was a problem regarding InputFormatter and showing invalid strings. I'll try to release an update very soon if I can make it work. Maybe within 2-3 days.

**Comment by adar2378** [comment]
Please update to the latest one 8eadff1
