### ISSUE TITLE
Requirement for 'readOnly' attrubutes

### ISSUE THREAD

**Issue by NachiketGohil** [adar2378/pin_code_fields#192]
### It's a Feature Request.
I came across this plugin around 6 months ago, and it was really nice after looking its **Featurefulness**. However in some case developer don't want to open the system keyboard and wanted to insert their custom Keyboard that suits app theme.
For this i have used this plugin in my project directory _(not added in pubspec.yaml)_. I also wanted to add custom keyboard as well as this plugin for better UI for **OTP Login**. So I added `readOnly` attribute to hide system keyboard.

Now see the efforts, just only for 1 attribute I had to add this plugin into project directory, **If You people can add this attribute**, then the use case of this plugin will be Rise Drastically.

**Comment by adar2378** [comment]
Added in 7.3.0
