### ISSUE TITLE
PinCodeTextField not importing?

### ISSUE THREAD

**Issue by milanobrenovic** [adar2378/pin_code_fields#195]
After adding the `pin_code_fields: ^7.2.0` version in the `pubspec.yaml` file the widget `PinCodeTextField` isn't importing. It can't find it, i tried to add the import manually and it simply cannot find it. What's wrong?

**Comment by adar2378** [comment]
Can you try to run `flutter pub get` command and see if there is any errors?

**Comment by flutteresbolivia** [comment]
Sometimes the code editor is bugged, try closing it and reopening it.

**Comment by AbdHayek** [comment]
`Mac User` In Android Studio go to File -> Invalidate caches/ restart -> Confirm 
Then retry to import the library again in your class

**Comment by malzariey** [comment]
> `Mac User` In Android Studio go to File -> Invalidate caches/ restart -> Confirm
> Then retry to import the library again in your class

Works as well on Windows
