### ISSUE TITLE
The method 'dependOnInheritedWidgetOfExactType' was called on null.

### ISSUE THREAD

**Issue by CanFor** [adar2378/pin_code_fields#196]
The following NoSuchMethodError was thrown building PinCodeTextField(dirty, dependencies: [_EffectiveTickerMode], state: _PinCodeTextFieldState#2525a(tickers: tracking 2 tickers)):
The method 'dependOnInheritedWidgetOfExactType' was called on null.
Receiver: null
Tried calling: dependOnInheritedWidgetOfExactType<_InheritedTheme>()

**Comment by CanFor** [comment]
Error due to self - passing context

**Comment by musaatalay1** [comment]
hello, im having this issue, how can i fix this?

**Comment by ZOALSD** [comment]
hello I'm have same issue , how resolved @CanFor @musaatalay1
