### ISSUE TITLE
TextEditingController disposed flutter_bloc error

### ISSUE THREAD

**Issue by flutteresbolivia** [adar2378/pin_code_fields#198]
I am using flutter_bloc and when I update some value and it refreshes in my BlocBuilder I get this error.

`A TextEditingController was used after being disposed. Once you have called dispose() on a TextEditingController, it can no longer be used.`

**Comment by adar2378** [comment]
I'd suggest you to provide a `TextEditingController` from outside and set the value for `automaticallyDisposeControllers` to `false`

FocosNode and TextEditingController will get disposed automatically. Use autoDisposeControllers = false to disable it.
