### ISSUE TITLE
Bug: Impossible to open the keyboard again

### ISSUE THREAD

**Issue by alevittoria** [adar2378/pin_code_fields#2]
Hello, there is a problem with the opening of the keyboard.
After you have focused the pin code if you press the Android back button to close the keyboard, you can't focus pin code again and open the keyboard.

**Comment by adar2378** [comment]
I'll check that soon. Thanks

**Comment by dungnv2602** [comment]
> Hello, there is a problem with the opening of the keyboard.
> After you have focused the pin code if you press the Android back button to close the keyboard, you can't focus pin code again and open the keyboard.

I can confirm this, got them same bug.

**Comment by adar2378** [comment]
Yeah, I've found the bug! Will update it tonight :)

**Comment by adar2378** [comment]
https://pub.dev/packages/pin_code_fields/versions/2.0.3
Update to the new version! Hopefully, that bug is gone.
