### ISSUE TITLE
Validation error message styling

### ISSUE THREAD

**Issue by prakash51** [adar2378/pin_code_fields#203]
How to style validation error message. In TextFormField we have errorStyle property . For pin code fields I am just seeing errorTextSpace.

**Comment by okelloEnos** [comment]
Yeah i second this issue.  A quick suggestion you can make the Validator function have a return type of Text() Widget.

**Comment by adar2378** [comment]
I have not been able to focus that much yet. Very busy with work. For a quick fix you can fork the repo and update the code here accordingly, https://github.com/adar2378/pin_code_fields/blob/880e31dfbcd7d6c4eab4274589c9f363c60db542/lib/src/pin_code_fields.dart#L732
