### ISSUE TITLE
IOS autofill

### ISSUE THREAD

**Issue by NestorDevs** [adar2378/pin_code_fields#205]
I wanted to ask if it already supports autofill on the ios keyboard .... I am using it but I have no success in showing me the otp on my iphone keyboard ... I read here that there are several open issues and I like it package but it does not help me if it does not autocomplete from the keyboard in ios

**Comment by NestorDevs** [comment]
hello could not in this package I used this ...
https://pub.dev/packages/sms_autofill 
resolvio todos los problemas.

**Comment by irakalaputenko** [comment]
sms_autofill work with Android. What about iOS?

**Comment by nestorDev2021** [comment]
in BOTH SO ... just keep in mind the way you send the message in ios. .... must include keywords ... such as CODE, PASSWORD, OTP ... and so on

**Comment by kurtiev** [comment]
@nestorDev2021 is that necessarry to generate hash of app? Like that:  `FA+9qCX9VSu`. This  described in [docs](https://developers.google.com/identity/sms-retriever/verify#1_construct_a_verification_message)  or OTP keyword inside message can be enough?
