### ISSUE TITLE
Not working on flutter 2.5

### ISSUE THREAD

**Issue by darwin-morocho** [adar2378/pin_code_fields#208]
After upgrade to flutter 2.5 this package has a strange behavior like duplicated values for each input

**Comment by CoMatu** [comment]
Not work next field focus after input into first field...

**Comment by adar2378** [comment]
Does it happen for every platform? I am trying to find some time for debugging. I'll look into it soon but can not give a proper deadline.

**Comment by darwin-morocho** [comment]
> Does it happen for every platform? I am trying to find some time for debugging. I'll look into it soon but can not give a proper deadline.

yes it is happening on Android and iOS

**Comment by GitHelge** [comment]
Are you using a real device or the simulator? - There is an open flutter issue for the simulator: https://github.com/flutter/flutter/issues/86565

**Comment by darwin-morocho** [comment]
> Are you using a real device or the simulator? - There is an open flutter issue for the simulator: [flutter/flutter#86565](https://github.com/flutter/flutter/issues/86565)

I've tested on simulator and real iOS and Android devices and the behavior is the same

**Comment by GitHelge** [comment]
I did not notice any strange behaviour yet (Started using the lib yesterday with flutter 2.5.0). Can you provide a small sample what behaves awkward?

**Comment by ChristopheFlimo** [comment]
I am also having issues since updating to 2.5
Pin needs to be entered backward.
To enter ABCD, I now need to type DCBA.
Tested on flutter web.

**Comment by GitHelge** [comment]
Hmm to be honest I dont have any problems using flutter 2.5.0/2.5.1 with this library. Are you sure the problem is not caused by your implementation? Following works fine for me (ios simulator and real device... not 100% sure about android because i normally dont use the android emulator)

```
PinCodeTextField(
  autoFocus: true,
  enablePinAutofill: false,
  beforeTextPaste: (value) {
    if (onPaste != null) onPaste!(value);
    return false;
  },
  appContext: context,
  length: 6,
  obscureText: obscureText,
  useHapticFeedback: true,
  autoDismissKeyboard: true,
  animationType: AnimationType.scale,
  showCursor: false,
  mainAxisAlignment: MainAxisAlignment.center,
  pinTheme: PinTheme(
    shape: PinCodeFieldShape.underline,
    fieldHeight: 50,
    fieldWidth: fieldWidth,
  ),
  onCompleted: (value) {
    if (onComplete != null) onComplete!(value);
  },
  onChanged: (value) {
    if (onChange != null) onChange!(value);
  },
  );
```

**Comment by maxakak1998** [comment]
Such a weird bug, you cant do the trick by set enablePinAutofill =false, default is true.

**Comment by ChristopheFlimo** [comment]
We got it working, it wasn't related, but just a coincidence.

**Comment by darwin-morocho** [comment]
The problem is when you pass a `TextEditingController` to the widget and in the onChange callback you call to 
```
controller.text = value;
```

then you have a strange behavior

**Comment by ahkela21** [comment]
> Not work next field focus after input into first field...

having this problem too, any solution or workaround

**Comment by skripsimu** [comment]
in flutter version 2.5.3
android device, after entering the first field then move the focus to the second field then when we enter the input in the second field no value is entered.

iOS device, the input is reversed, so when we input 2345 it becomes 5432

**Comment by mchilvers** [comment]
Hiya! We are also seeing weirdness after upgrading to Flutter 2.5 - even when using the example code.

To reproduce:-

1) Use the code from the example on pub.dev
2) Enter values into the pin code field.
3) Tap the 'Clear' button (fields clear correctly)
4) Tap the first digit of the pin code field
5) The previous values reappear.

**Comment by ajumalp** [comment]
> in flutter version 2.5.3 android device, after entering the first field then move the focus to the second field then when we enter the input in the second field no value is entered.
> 
> iOS device, the input is reversed, so when we input 2345 it becomes 5432

@mchilvers 
I found this issue happens when we assign controller to PinCodeTextField. A workaround is to use the onCompleted event and update the controller.

```dart
// controller: widget.tfOTP,
onCompleted: (text) => widget.tfOTP.text = text,
```
