### ISSUE TITLE
[Request] Option to autoclear on error

### ISSUE THREAD

**Issue by mludovico** [adar2378/pin_code_fields#216]
It would be useful to have an option to automatically clear the field on pin error. Specially if one is managing the text value outside of the view, like using mobx or similar and do not want to create a TextEditingController. As error animation uses a stream it can be listened to just once. So it could use a bool flag to conditionally call `_textEditingController?.clear();` inside of the listen callback and set the focus back to first field. I could send a PR if you like.

**Comment by betoflakes** [comment]
I came here with the same case.
