### ISSUE TITLE
[ISSUE] IOS: pin code fields keep storing input after calling TextEditingController.clear()

### ISSUE THREAD

**Issue by PTLam25** [adar2378/pin_code_fields#222]
Hi! I would like to clear inputs when clicking on the text button "Resend code". 

So I use PinCodeTextField widget with TextEditingController and on **onPressed** callback of  "Resend code" i call TextEditingController.clear(). After it, UI is updated but when I focus on pin code fields old inputs are appeared. Please watch the video:
https://user-images.githubusercontent.com/83693224/145571422-9c607677-2a69-4ce3-a68a-31c5c427e809.mp4

This bug is only in IOS, in Android it works well.

**Comment by NguyenDinhTruong97** [comment]
Same here.

**Comment by enriquejuan2** [comment]
I also getting the same issue on IOS, i tried enablePinAutoFill = false but i still get the issue

**Comment by ruslanbadaev** [comment]
@NguyenDinhTruong97 I adore you))
