### ISSUE TITLE
overflowing in small devices (each field width 52, height 52)

### ISSUE THREAD

**Issue by Nagendra7509** [adar2378/pin_code_fields#227]
device size - 360*640

![image](https://user-images.githubusercontent.com/59285838/148017609-6d93d3a1-0218-4663-8d4d-d9283264d715.png)

**Comment by Nagendra7509** [comment]
resolved

**Comment by Add00w** [comment]
For temporary solution wrap your pinfield widget with ListView

**Comment by vrman** [comment]
same problem here , i dont like to use ListView to fix this.
i think its better to have a option for auto resize width and height to parent size.

**Comment by Add00w** [comment]
> same problem here , i dont like to use ListView to fix this. i think its better to have a option for auto resize width and height to parent size.

try something like this: `SizedBox(
                              width: MediaQuery.of(context).size.width * yourSize, child:form..Pincode)`
