### ISSUE TITLE
 I'm not able to edit the otp value entered by tapping on the particular block. Auto focus on last block

### ISSUE THREAD

**Issue by sakina1403** [adar2378/pin_code_fields#232]
Hey, firstly thank you for the package I have been able to use it well for my use cases so far.

I am facing one issue, it's that I am not able to focus on a particular block. For example, I have entered an incorrect value in box 2 then I have to delete all the values from block 4 till block 2 to re-enter the value. The cursor seems to focus on the last block always.

Is there any property that I can pass to enable this? I looked into the package code but couldn't find the solution.

Hoping for a response, thanks for your time & effort.

**Comment by mahmoud-atef-eden** [comment]
I'm facing the same problem any updates?

**Comment by kdokhanx98** [comment]
same problem

**Comment by kdokhanx98** [comment]
we want the same library to fix this error instead of moving to other libraries.

**Comment by Nagendra7509** [comment]
I'm facing the same problem

**Comment by Nagendra7509** [comment]
@adar2378 is it possible to add this feature??

**Comment by Nagendra7509** [comment]
@sakina1403 

`flutter_otp_text_field` in this package I am able to edit individual fields only. 

any other suggestions?

**Comment by DohanKim** [comment]
can we reopen this?

**Comment by Alrfati-HazemY** [comment]
Any update on this issue?
