### ISSUE TITLE
Can paste params that are being defined that invalid.

### ISSUE THREAD

**Issue by enzodanjour** [adar2378/pin_code_fields#235]
When I define an input type and try to type something that is outside the rule, it blocks, in this situation it works perfectly.

The problem occurs when I try to paste some text that I couldn't, for example: when I define that it can only numbers but I happen to copy some text outside the application, and I click to paste it, so even with the security rule it pastes.

![Screenshot from 2022-02-03 22-31-08](https://user-images.githubusercontent.com/35856303/152457736-aff04bcb-1f84-4b26-be53-caed91133bd8.png)

![Screenshot from 2022-02-03 22-32-07](https://user-images.githubusercontent.com/35856303/152457709-2f4ee134-9270-4792-b283-57289ea5b62e.png)

![Screenshot from 2022-02-03 22-33-06](https://user-images.githubusercontent.com/35856303/152457872-ae65c940-e0a9-461a-ba07-a97f6f5c930a.png)

![Screenshot from 2022-02-03 22-43-04](https://user-images.githubusercontent.com/35856303/152458608-af906dac-3018-4a81-b88b-5eed3374b480.png)

**Comment by barteksc** [comment]
Use `beforeTextPaste` property, it's documented in readme:
```dart
/// Callback method to validate if text can be pasted. This is helpful when we need to validate text before pasting.
/// e.g. validate if text is number. Default will be pasted as received.
final bool Function(String? text)? beforeTextPaste;
```
