### ISSUE TITLE
Pin_code_fields issue for RTL languages 

### ISSUE THREAD

**Issue by Add00w** [adar2378/pin_code_fields#237]
We want the `PinInputFields` direction always to be from left to right, so we wrapped it with `Directionality` widget with  `TextDirection.ltr`, which fixed the first issue for us but raised another issue by showing the error text from the left too which is not correct for RTL languages e.g. Arabic and Hebrew.

**First issue**:
![first issue](https://user-images.githubusercontent.com/35359329/152972553-39f3bf1e-3125-4591-b293-650e953888b6.png)

Then solved using Directionality widget but raised a new issue which is an error message showing from left:
![wrong text direction](https://user-images.githubusercontent.com/35359329/152973252-79220c70-fcd8-41ad-80a9-dc96c2ece11d.png)

**Expected result**:
![fixed text direction](https://user-images.githubusercontent.com/35359329/152973468-f57f755e-a4a2-4489-8454-29ccb97f967b.png)

**Comment by adar2378** [comment]
Great work! Thanks.
