### ISSUE TITLE
Flickers on tapping

### ISSUE THREAD

**Issue by Graaggas** [adar2378/pin_code_fields#238]
Good day!
The screen flickers when I tap on fields. Looks like widget re-build. Why is this happening?
OnTap and OnChanged do nothing.

<img width="434" alt="image" src="https://user-images.githubusercontent.com/24309240/153120471-ff9dcd27-c758-467d-95cd-e86728618635.png">

https://user-images.githubusercontent.com/24309240/153120367-3adf9fb6-8109-4b09-a3be-f2bc231a3c6e.mp4

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-arm, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.0)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by adar2378** [comment]
New version has been released with autoUnfocus. Thanks for the great work!
