### ISSUE TITLE
Validation failure message appears behind fields

### ISSUE THREAD

**Issue by lbk9** [adar2378/pin_code_fields#243]
This only applies when the `autovalidateMode` is set to `AutovalidateMode.disabled`, if the validation fails then the message you provide appears behind the fields. If the mode is set to `onUserInteraction` then the message appears as intended.

Here is my implementation 
```
    return PinCodeTextField(
      appContext: context,
      length: 6,
      animationType: AnimationType.scale,
      validator: validator,
      keyboardType: TextInputType.number,
      onChanged: (value) => onPinEnetered(value),
      autovalidateMode: AutovalidateMode.disabled,
      pinTheme: PinTheme(
        shape: PinCodeFieldShape.box,
        borderRadius: BorderRadius.circular(10),
        fieldHeight: 50,
        fieldWidth: 40,
        activeFillColor: Colors.white,
      ),
    );
```

Parent widget tree
```
PincodeField(
                            onPinEnetered: (pin) {
                              viewModel.pinCode = pin;
                            },
                            validator: (val) {
                              if (val!.length != 6) {
                                return 'Invalid pin length';
                              }
                              return null;
                            },
                          )
```
![Simulator Screen Shot - iPhone 11 Pro - 2022-02-22 at 09 57 39](https://user-images.githubusercontent.com/58972669/155108333-1a816602-c7d5-479e-b4d5-8ad921b12d76.png)

**Comment by adar2378** [comment]
currently for `AutoValidate.disabled` we don't put the extra space. Seems like need to set it to if the validator is null only then the space should not be shown. Thanks for reporting. Hoping to release a new build this weekend.

**Comment by lbk9** [comment]
I could raise a PR for it if you like. Seems like this section of code is the problem
`height: (widget.autovalidateMode == AutovalidateMode.disabled &&
                widget.validator == null)`
So that the errorHeight is only not added when the validator is null.
