### ISSUE TITLE
is it able to change boxShadows out of the box?

### ISSUE THREAD

**Issue by ValeriusGC** [adar2378/pin_code_fields#245]
Hi! Is it possible to control shadows color when digits are filled, i.e.
![Screenshot from 2022-03-09 09-53-36](https://user-images.githubusercontent.com/3320861/157375657-5bef4c7c-b465-4a36-a96b-bc404ffb723b.png)

**Comment by adar2378** [comment]
Currently only has global boxShadows. But not for different states of the pin cells

**Comment by ValeriusGC** [comment]
> Currently only has global boxShadows. But not for different states of the pin cells
well, is there make it possible in nearest  versions?
