### ISSUE TITLE
OTP autofill on iOS

### ISSUE THREAD

**Issue by CoderNamedHendrick** [adar2378/pin_code_fields#252]
OTP autofill doesn't work on iOS and this is getting logged in my console
```
Can't find keyplane that supports type 4 for keyboard iPhone-PortraitTruffle-NumberPad; using 27071_PortraitTruffle_iPhone-Simple-Pad_Default
```

For keyboardType I'm using TextInputType.number

**Comment by campovski** [comment]
Same here.

**Comment by Peng-Qian** [comment]
same here, any updates?

**Comment by Add00w** [comment]
> OTP autofill doesn't work on iOS and this is getting logged in my console
> 
> ```
> Can't find keyplane that supports type 4 for keyboard iPhone-PortraitTruffle-NumberPad; using 27071_PortraitTruffle_iPhone-Simple-Pad_Default
> ```
> 
> For keyboardType I'm using TextInputType.number

Use Software Keyboard for simulators.

**Comment by CoderNamedHendrick** [comment]
> > OTP autofill doesn't work on iOS and this is getting logged in my console
> > ```
> > Can't find keyplane that supports type 4 for keyboard iPhone-PortraitTruffle-NumberPad; using 27071_PortraitTruffle_iPhone-Simple-Pad_Default
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For keyboardType I'm using TextInputType.number
> 
> Use Software Keyboard for simulators. Uncheck the connect hardware keyboard.

Same is happening  on a physical device.

**Comment by SreehariRajeevFSS** [comment]
Reopen issue
