### ISSUE TITLE
Can't achieve borderRadius

### ISSUE THREAD

**Issue by hiruthicShaSS** [adar2378/pin_code_fields#259]
![image](https://user-images.githubusercontent.com/56349092/168252426-5f40b355-0b12-4138-aa76-d2ff03d2e2b4.png)
How to achieve the textboxes like above image with border radius.

I have tried adding:
```dart
PinTheme(
    borderRadius: BorderRadius.circular(20),
)
````

but it doesn't seem to work.

**Comment by khang-dev** [comment]
@hiruthicShaSS how did you do it at the end ?

**Comment by hiruthicShaSS** [comment]
```bash
flutter clean
flutter pub get
```

I think its mostly because the application I was developing was already had so many dependency and some time this happens with other packages too. Restarting the IDE and doind a fresh install of packages resolved the issue

**Comment by yancaidev** [comment]
Hot reason is that the hot reload is not working on `PinCodeTextField`。Give it a `key` solved the problem when debug.
```
PinCodeTextField(
   key: GlobalKey(),
)
```

**Comment by Moskaoud** [comment]
> Hot reason is that the hot reload is not working on `PinCodeTextField`。
