### ISSUE TITLE
Weird gap between confirm dialog content and question mark

### ISSUE THREAD

**Issue by the-eric-kwok** [adar2378/pin_code_fields#260]
<img width="255" alt="image" src="https://user-images.githubusercontent.com/16463312/168879473-14f9cbb0-230c-4a7b-aa6d-5853701e2e7f.png">

PS: The question mark is not in my `dialogContent` argument and I think dialog should not add this for me.

**Comment by dennismuench** [comment]
@the-eric-kwok that's the default textStyle color. Try `textStyle: Theme.of(context).textTheme.bodyMedium` or  `textStyle: TextStyle(color: Theme.of(context).colorScheme.onSurface)`.

The question mark gets added by default. But I agree, this shouldn't be done by the widget. It makes it difficult to translate to certain languages, like Arabic or Chinese. It would make more sense to let `dialogContent` receive a `Widget Function(String?)` so you can construct the dialogContent yourself.

Maybe create a `dialogContentBuilder` option to stay backwards compatible. (e.g. `Widget Function(BuildContext, String?)`)

**Comment by arbazadam** [comment]
Is there a way to get rid of the dialog and only have the pasting capability?
