### ISSUE TITLE
Issues with pin_code_fields_test

### ISSUE THREAD

**Issue by akadatsky** [adar2378/pin_code_fields#261]
I use Flutter version 2.10.2  and Dart version 2.16.1 and have issues with tests:
1) Test failed on this line of code `await tester.pumpAndSettle();` with error `pumpAndSettle timed out`.
Maybe on the previous version of Flutter, it works but it looks like the Flutter team changed something, and now it goes into a loop with some infinity animation. 
2) Even if remove this issue test fils with the error `Golden "golden_test_1.png": Pixel test failed, 0.02% diff detected.`

**Comment by datake914** [comment]
It is probably due to the repeating cursor animation
https://github.com/adar2378/pin_code_fields/blob/master/lib/src/pin_code_fields.dart#L363

If the `showCursor` option is set to `false`, I think this problem is resolved.
