### ISSUE TITLE
Unable to re-focus after app was in background

### ISSUE THREAD

**Issue by dennismuench** [adar2378/pin_code_fields#262]
This only happens when `autoUnfocus: false`. Tested on Android (device).
This occurs independently from other settings (such as `focusNode` or `autoFocus`).

If the pin_code_fields looses focus through the app going to background, the only way of re-focusing (getting the keyboard back up) is to paste something.

Flutter: 3.0.0
Android SDK version 32.0.0

This is a minimal configuration that still reproduces this phenomenon.

```dart
PinCodeTextField(
    appContext: context,
    length: 6,
    autoUnfocus: false,
    onChanged: (_) {},
]);
```

**Comment by allanwolski-openco** [comment]
Why was this closed without a solution?
Same problem here.
