### ISSUE TITLE
Confusing naming for errorAnimationController

### ISSUE THREAD

**Issue by Alex-Usmanov** [adar2378/pin_code_fields#268]
The name of the field `errorAnimationController` is quite confusing. 

First of all, Flutter SDK already ships with a class called `AnimationController`, which is used to control animation. This field has nothing to do with `AnimationController`, is actually a `StreamController` that dispatches animation types for the field. 

I suggest renaming for this field to prevent muddling up with `AnimationController`, which makes the API less intuitive.
Instead, I would call it something along `errorAnimationTypeController`, or `errorAnimationTypeStreamController`.

(Also, use of StreamControllers as parameters in widgets is uncommon in the widgets library that is shipped with the framework. Instead, the SDK conforms to the pattern of `Controllers`, like `TextEditingController`, that use functions instead of reactive programming => easier to grasp for beginners)

**Comment by Add00w** [comment]
> The name of the field `errorAnimationController` is quite confusing.
> 
> First of all, Flutter SDK already ships with a class called `AnimationController`, which is used to control animation. This field has nothing to do with `AnimationController`, is actually a `StreamController` that dispatches animation types for the field.
> 
> I suggest renaming for this field to prevent muddling up with `AnimationController`, which makes the API less intuitive. Instead, I would call it something along `errorAnimationTypeController`, or `errorAnimationTypeStreamController`.
> 
> (Also, use of StreamControllers as parameters in widgets is uncommon in the widgets library that is shipped with the framework. Instead, the SDK conforms to the pattern of `Controllers`, like `TextEditingController`, that use functions instead of reactive programming => easier to grasp for beginners)

Since you have all this knowledge you can make the changes you see are needed and make PR to the maintainer.
Which is the beauty of the open source.
