### ISSUE TITLE
dispose focusNode and controller

### ISSUE THREAD

**Issue by pqsky7** [adar2378/pin_code_fields#28]
Hi,

Thanks for your awesome plugin! 

I am confused about dispose process. I think this plug-in has auto dispose of focusNode and controller, so we cannot call focusNode.dispose() and controller.dispose() in our stateful widget (even If we assign a focus node or controller for the plug-in). Am I right about this?

**Comment by adar2378** [comment]
It automatically disposes when the widget gets disposes.
