### ISSUE TITLE
Web version request

### ISSUE THREAD

**Issue by Fluics** [adar2378/pin_code_fields#29]
Is it planned to adapt to web use? Not working right now: keyboard input not accepted

**Comment by adklempner** [comment]
I'm experiencing the same error when using `2.3.0+3`
Can confirm that keyboard input on web works for version `2.3.0+2`, so it looks like `2.3.0+3` introduced the breaking change.

@Fluics for the time being, you can specify `pin_code_fields: 2.3.0+2` in your `pubspec.yaml`

**Comment by adar2378** [comment]
Hello guys, I'm on vacation right now. I've not tested on web yet. I'll check next week hopefully.

**Comment by nheumann** [comment]
I'm currently using the latest version `3.0.1` with Chrome and the keyboard doesn't work. Is web support planned or in progress?

**Comment by robinbonnes** [comment]
The workaround that worked for me was keeping the input value not empty.

1. Use a controller to always make sure there is a space in the input value:

```
TextEditingController controller = TextEditingController();
```

2. Set the value in initState:
```
void initState() {
  controller.text = " ";
}
```

3. Make sure it won't be empty by adding the following in the `onChanged` function from the `PinCodeTextField` widget:

```
onChanged: (String value) {
  if(value.isEmpty) {
    controller.text = " ";
  }
}
```

**Comment by robinbonnes** [comment]
Have to note, the space gets removed again by adding the following to the `inputFormatters` parameter of the `PinCodeTextField` widget:

```
BlacklistingTextInputFormatter(new RegExp('[ ]'))
```

This makes sure the input doesn't overflow. However this fix doesn't work for Chrome on Android. It starts bugging on third char.

**Comment by adar2378** [comment]
Added support for Flutter-web!
