### ISSUE TITLE
The following assertion was thrown while dispatching notifications for FocusNode

### ISSUE THREAD

**Issue by bambinoua** [adar2378/pin_code_fields#292]
The following assertion was thrown while dispatching notifications for FocusNode:
```
setState() called after dispose(): _PinCodeTextFieldState#8937e(...)
```
The issue occurred in a line 336 (method `initState`) of `pin_code_fields.dart` file.
```dart
@overide
void initState() {
  super.initState();
  ...
  _focusNode!.addListener(() {
    setState((){}); // <-- line 336
  });
  ...
}
```

**Comment by Karlen96** [comment]
the focusNode is being disposed twice: once during navigation and once again from outside.
The package has an "automatic dispose" feature, that can be set to false for manual disposal.
