### ISSUE TITLE
Feature request: autofocus and manually keyboard closing.

### ISSUE THREAD

**Issue by alevittoria** [adar2378/pin_code_fields#3]
Can you give the capability to autofocus the pin code on opening?
Another minor feature is to give the capability to close the keyboard manually when the user writes the last character.
In general thx, I really like this library.

**Comment by adar2378** [comment]
Yeah, I can totally add the autofocus feature 👍 I've talked to my UX designer friend before making this. He suggested that the keyboard should close after the user have inputted all the values. So it is going to be like that for now. But you can always edit the source file and make use of it on your own will ;) Cheers.
