### ISSUE TITLE
Set State is being called after disposed from Animation/Timer callback

### ISSUE THREAD

**Issue by shaurya-src** [adar2378/pin_code_fields#302]
On changing the state of the screen with PinCodeTextField, this error is being thrown:

```
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for FocusNode:
setState() called after dispose(): _PinCodeTextFieldState#28fbb(lifecycle state: defunct, not mounted, tickers: tracking 0 tickers)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
```

**Comment by bambinoua** [comment]
It looks like this issue was [fixed](https://github.com/adar2378/pin_code_fields/blob/2500700d0670e36859d79965d1bfbf22d77de936/lib/src/pin_code_fields.dart#L353) but version is not updated on `pub.dev`.

**Comment by bambinoua** [comment]
@adar2378 please update the version on `pub.dev`.

**Comment by esentis** [comment]
Do we have an ETA for the update ? :)

**Comment by subzero911** [comment]
+1, need this fix

I currently have the similar error, when I show and hide the pin field while requesting the focus:
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/12999702/220331844-75c096c8-852e-4cbc-9d0d-452d21aaae48.png">

**Comment by bambinoua** [comment]
For now the only "fix" is:
```yaml
dependency_overrides:
  pin_code_fields:
    git:
      url: https://github.com/adar2378/pin_code_fields.git
      ref: master
```

**Comment by esentis** [comment]
This is still not updated.

**Comment by esentis** [comment]
Commenting for activity. The issue is still here.

**Comment by subzero911** [comment]
Seems like an author had abandoned this package...
Is anyone here who's willing to fork it and continue supporting?

**Comment by bambinoua** [comment]
@adar2378 we hope the new `8.0.1` fixes this issue? :)

**Comment by adar2378** [comment]
@subzero911 I have not abandoned it. I am looking for maintainers if someone is interested because I have been busy with life and can not find enough time. 

@bambinoua Yes, 8.0.1 should fix it.
