### ISSUE TITLE
Allow paste without confirmation dialog

### ISSUE THREAD

**Issue by rbarzel** [adar2378/pin_code_fields#306]
Hi, 

Nice plug-in, thank you! 
It would be great there was an option to allow the user to paste without any confirmation dialog.

**Comment by rbarzel** [comment]
My mistake, seems the plug-in works exactly as I want it to.

**Comment by rbarzel** [comment]
```
PinCodeTextField(
   beforeTextPaste: (_) => false,
   ...
)
```

**Comment by cmoralesweb** [comment]
> @ironclock
> 
> ```
> PinCodeTextField(
>    beforeTextPaste: (_) => false,
>    ...
> )
> ```

That blocks pasting altogether, not only the dialog.
