### ISSUE TITLE
Rename appContext to context

### ISSUE THREAD

**Issue by subzero911** [adar2378/pin_code_fields#321]
`appContext` parameter name is incorrect.
There's no any "appContext" in Flutter (unlike native Android).
It has `context` which is basically a pointer to a current Element in the element tree. It's used primarily to lookup nearest InheritedWidget above (all the `.of` methods like `Theme.of(context)`, `MediaQuery.of(context)`) So the parameter name should be just `context`.

**Comment by subzero911** [comment]
:(

**Comment by subzero911** [comment]
bump

**Comment by Imesh7** [comment]
@adar2378 do you have any idea to do this?
