### ISSUE TITLE
Border radius does not work with Underline shape

### ISSUE THREAD

**Issue by sosualfred** [adar2378/pin_code_fields#338]
```
pinTheme: PinTheme(
    borderRadius: BorderRadius.circular(20),
    shape: PinCodeFieldShape.underline,
    fieldHeight: 50,
    fieldWidth: 60,
    borderWidth: 3,
),
```       

After specifying shape to be `PinCodeFieldShape.underline` and giving border radius, the border radius is not applied.

![image](https://github.com/adar2378/pin_code_fields/assets/22264939/078c8083-30ce-4d38-9de4-1b1ac59bef9d)

**Comment by loushiano** [comment]
i got the same issue. its a bug in the code

**Comment by loushiano** [comment]
opened pr for it: https://github.com/adar2378/pin_code_fields/pull/346
