### ISSUE TITLE
support iOS keyboard pin auto fill

### ISSUE THREAD

**Issue by sooxt98** [adar2378/pin_code_fields#37]

**Comment by adar2378** [comment]
As far as I remember, it does support it. If you have an autofill code, then gapping on it should paste the code

**Comment by sooxt98** [comment]
![image](https://user-images.githubusercontent.com/13378059/76592118-5576bc80-652d-11ea-8ec1-cc1bc8675247.png)

It works with normal text field like this, but not with this library @adar2378

**Comment by adar2378** [comment]
Does the keyboard show it? Or after tapping on the "From Messages" does nothing?

**Comment by sooxt98** [comment]
the keyboard doesnt show "From Message"

**Comment by adar2378** [comment]
Ohho, I don't have an iPhone to test it with :( I'll see what I can do

**Comment by adar2378** [comment]
https://github.com/flutter/flutter/issues/13015#issuecomment-580076920
Okay, I found this. I hope this helps

**Comment by sooxt98** [comment]
@adar2378  i dont think is that, it's another issue lol

**Comment by adar2378** [comment]
Could you please show me the piece of code you used of the pin code widget?

**Comment by softmarshmallow** [comment]
any updates on this?

**Comment by adar2378** [comment]
The official autofill is available now
