### ISSUE TITLE
PinCodeTextField causes constant redraws

### ISSUE THREAD

**Issue by turulix** [adar2378/pin_code_fields#371]
When Adding PinCodeTextField to a screen it causes constant frame redraws, causing performance issues and making Integration testing impossible.

Flutter: v3.16.5
pin_code_fields: 8.0.1

Here is the Same Page with and without a PinCodeTextField from the flutter performance window:
Without:
![brave_1708228851](https://github.com/adar2378/pin_code_fields/assets/28957605/61cc4407-6d60-4c85-a2ab-3ff97c2a638a)

With:
![brave_1708228871](https://github.com/adar2378/pin_code_fields/assets/28957605/cd7e6f44-f753-45ce-aded-9b8a8d7a448e)

I couldn't figure out what causes this issue, but maybe you guys can figure it out.
My component looks something like this (some elements are commented out to ensure its not one of those causing the issue):
```dart
class RegistrationVerifyPhoneScreen extends StatelessWidget {
  const RegistrationVerifyPhoneScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final api = Get.find<Api>();
    final enteredPinController = TextEditingController();

    void onContinue() async {
       // Do some things here
    }

    return ScreenBase(
        child: Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Text(t.strings.registration.step_phone_verify,
            style: context.theme.textTheme.headlineSmall, textAlign: TextAlign.center),
        const Spacer(),
        PinCodeTextField(
          appContext: context,
          length: 6,
          // animationType: AnimationType.fade,
          // animationDuration: const Duration(milliseconds: 100),
          // backgroundColor: context.theme.scaffoldBackgroundColor,
          // enablePinAutofill: true,
          // keyboardType: TextInputType.number,
          // controller: enteredPinController,
          // pinTheme: PinTheme(
          //   shape: PinCodeFieldShape.box,
          //   borderRadius: BorderRadius.circular(5),
          //   selectedColor: context.theme.primaryColor,
          //   activeColor: Colors.black,
          //   errorBorderColor: context.theme.errorColor,
          //),
        ),
        const Spacer(),
        FilledButton(
          onPressed: onContinue,
          child: Text(t.strings.continuee),
        ),
      ],
    ));
  }
}

```

**Comment by Yagorundy** [comment]
I think I run into the same issue from this package @adar2378

**Comment by richanshah** [comment]
@turulix any update on this? , is it resolved?

**Comment by turulix** [comment]
I decided to implement my own, after waiting weeks without a response

**Comment by andrefedev** [comment]
> I decided to implement my own, after waiting weeks without a response, but even `showCursor: false` dosn't really make sence in my opinion (havn't tried it) but it updates at basically 60fps and a cursor blinking shouldn't do it that fast, comparing it to a normal text field which updates like every few frames

And why doesn't it make sense if you haven't even tried it?
