### ISSUE TITLE
onCompleted event is called before onChanged event

### ISSUE THREAD

**Issue by superakabo** [adar2378/pin_code_fields#38]
After entering a value into the last field of the pin code text field, the onCompleted event is triggered before the onChanged event.

To debug, just print out the values from these events.

**Comment by adar2378** [comment]
Looking at it asap

**Comment by superakabo** [comment]
> Looking at it asap
> Edit 1: Yeah Found it. But is it creating any problems while working with the widget?

Yes. Anyway i submitted a PR that resolves this.

**Comment by adar2378** [comment]
I appreciate your effort. Could you please tell me where did you face the problem with onCompleted being triggered first?

**Comment by superakabo** [comment]
> I appreciate your effort. Could you please tell me where did you face the problem with onCompleted being triggered first?

Sure. 

void setSMSCode(String smsCode) {
}

I used this function above to set the sms code entered by the user. It is triggered by the onChanged event. Whenever the last entry is made, the code sent to the server always mismatched.
