### ISSUE TITLE
How to change the colour of the errortext not appearing in the theme properties 

### ISSUE THREAD

**Issue by NestorDash** [adar2378/pin_code_fields#382]
I can't find where to take the textErrorColor feature as in the. Textformfield 

something like this

decoration: InputDecoration(
        errorStyle: GoogleFonts.poppins(
          color: AppColor.primary,
          fontSize: Sizes.dimen_16.sp,
        ),
        suffixIcon: Padding(
          padding: const EdgeInsets.only(right: 12),
          child: IconButton(
            highlightColor: AppColor.transparent,
            onPressed: onPressedIcon,
            icon: svgIcon ?? const SizedBox.shrink(),
          ),
        ),

**Comment by raulzanardo** [comment]
The color change if the theme is Dark or Light, but if I could specify the color it would better.
