### ISSUE TITLE
Keyboard does not show

### ISSUE THREAD

**Issue by praharshbhatt** [adar2378/pin_code_fields#4]
The keyboard does not show up after clicking on the widget, does not focus.
The widget seems to be disabled for some reason?
![Screenshot_1572288591](https://user-images.githubusercontent.com/30700808/67708399-1e6e9700-f9e2-11e9-804b-141ce4d6c5ba.png)

(This happens on the sample code too)

**Comment by adar2378** [comment]
https://pub.dev/packages/pin_code_fields/versions/2.0.3
Please update to the new version. Thanks!

**Comment by rdev-software** [comment]
@adar2378 I have version 2.1.1 and keyboard is not opening

**Comment by adar2378** [comment]
I've checked again. The keyboard is working fine. Could you please tell me how to reproduce this bug?

**Comment by EmmanuelVlad** [comment]
I've the same issue as @rdev-software, the problem comes from the `enabled` property set to `false` instead of `true` on the main TextField.

Currently running Flutter 1.12.5-pre.45
