### ISSUE TITLE
pinCodeField dispose dispose the TextEditingController 

### ISSUE THREAD

**Issue by rudys-oshin** [adar2378/pin_code_fields#40]
in my code i made a setState and change the field with a loading, this cause this field dispose method was called, it dispose my TextEditingController and when the loading finish and the pinCodeField is called again, the controller was disposed.

A TextEditingController was used after being disposed.

**Comment by adar2378** [comment]
okay. So the widget is getting removed from the tree and also disposed. I'll add a flag to enable auto-dispose. Thanks mate.

**Comment by adar2378** [comment]
But for quick workaround, you can use a stack with the loader and pincode fieild. When you want to see the loader just set the opacity to 1 else 0.

**Comment by rudys-oshin** [comment]
thanks, that was fast, i will try with the opacity, thanks again

**Comment by adar2378** [comment]
Added autoDisposeControllers flag to set the disposal automatic or manual in the lastest release, thanks.
