### ISSUE TITLE
Support FormValidators?

### ISSUE THREAD

**Issue by bobwiller** [adar2378/pin_code_fields#41]
I realize there is a mechanism to support some level of validation with the onChanged event, but any chance of supporting FormValidators so we can wrap this into the entire form validation lifecycle like a standard TextFormField?

Great Project btw, thank you for this.
Bob

**Comment by adar2378** [comment]
This is a great idea actually. Thanks for your suggestion. I'll try to implement this before the next update which might come next week or so.

**Comment by caioaao** [comment]
@adar2378 what's the status on this? I can help out if needed. 
btw, idk how you were planning on implementing it, but an idea could be to wrap the input on a `FormField` (like [TextFormField](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_form_field.dart#L121) is just a wrapped `TextField`)

**Comment by adar2378** [comment]
Hi, I've tried to do what you said but the problem is that we don't have much control over the error messages as they automatically show when the data is invalid. And that error message doesn't go with the aesthetic. 
I'd really appreciate your help if you can manage to make it work somehow.

**Comment by adar2378** [comment]
It has been added guys! Thanks for your valuable suggestions!
