### ISSUE TITLE
Unable to open the keyboard after closing

### ISSUE THREAD

**Issue by AlvaroVasconcelos** [adar2378/pin_code_fields#42]
After closing the keyboard is it not possible to open it again?

**Comment by adar2378** [comment]
It should open. If you're experiencing this problem then please let me know the version of the package you're using along with the code snippet, thanks for your contribution.

**Comment by AlvaroVasconcelos** [comment]
Flutter version:
[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [versÃ£o 10.0.18363.720], locale pt-BR)
Package version:
pin_code_fields: ^2.4.0
````dart
PinCodeTextField(
                autoFocus: true,
                focusNode: _focusNode,
                activeColor: Style.button_color,
                backgroundColor: Style.background_color,
                length: 6,
                obsecureText: false,
                onCompleted: (v) {
                  _recoveryController.sendCode();
                },
                animationType: AnimationType.fade,
                shape: PinCodeFieldShape.box,
                animationDuration: Duration(milliseconds: 300),
                borderRadius: BorderRadius.circular(5),
                fieldHeight: MediaQuery.of(context).size.width * 0.2,
                fieldWidth: MediaQuery.of(context).size.width * 0.1,
                onChanged: (value) {
                  _recoveryController.validarSmsData.changeCode(value);
                },
              )
````

**Comment by adar2378** [comment]
Hi, I just checked it is working fine. You should be able to open the keyboard again after closing.
I used Flutter's latest stable build. I think since you're using the beta channel, it could cause some unknown problems.

**Comment by AlvaroVasconcelos** [comment]
The problem really is in the Flutter **beta** version. Thank you very much.
