### ISSUE TITLE
Can you show the focus box cursor?

### ISSUE THREAD

**Issue by HeebeLee** [adar2378/pin_code_fields#43]
Now the focus is on the change between the outer box and the bottom color, but in fact, it should conform to the characteristics of the input box and show the position of the cursor, which will make it easier to see the current input position.

I found that there is no way to set it through parameters. I hope to add this feature.

It's a great project, so I want her to be perfect. Thank you

**Comment by adar2378** [comment]
I'll try to add that. Thanks for your suggestion.

**Comment by adar2378** [comment]
Added
