### ISSUE TITLE
Unable to open keyboard

### ISSUE THREAD

**Issue by Emrage** [adar2378/pin_code_fields#51]
When pressing the back button to close the keyboard, you can't open the keyboard back up again.

**Comment by adar2378** [comment]
In the next update, this bug should be gone. If your need is urgent I suggest please use the package from the master branch.

**Comment by Emrage** [comment]
> In the next update, this bug should be gone. If your need is urgent I suggest please use the package from the master branch.

Thank you.

**Comment by adar2378** [comment]
Here is an example of using from GitHub:
`dependencies:
  plugin1:
    git:
      url: git://github.com/flutter/plugin1.git
`
