### ISSUE TITLE
Allow modifying the shown theme color for the last input field

### ISSUE THREAD

**Issue by nheumann** [adar2378/pin_code_fields#54]
When completing all input fields the last field gets displayed in the selectedColor of the specified pin theme, as you can see here (`selectedColor` is blue and `activeColor` is green in this case): 

![Screenshot 2020-05-11 at 15 57 05](https://user-images.githubusercontent.com/52076234/81569858-1d122400-93a0-11ea-831f-3622c47e7a7d.png)
I need the last input field to be displayed in the `activeColor` though, so that it's color matches the color of all other fields and therefore indicates that the pin input is completed. This is what I expect when all pin fields are entered:
![Screenshot 2020-05-11 at 16 02 52](https://user-images.githubusercontent.com/52076234/81570457-e7216f80-93a0-11ea-9a87-6f0df2affea5.png)
The required change concerns the following private method from `lib/pin_code_fields.dart`. For this one could add an attribute to the PinCodeTextField widget that determines what color gets returned for the last input field in `_getColorFromIndex()` instead of generically displaying the last input as selected.
```
// selects the right color for the field
  Color _getColorFromIndex(int index) {
    if (!widget.enabled) {
      return _pinTheme.disabledColor;
    }
    if (((_selectedIndex == index) ||
            (_selectedIndex == index + 1 && index + 1 == widget.length)) &&
        _focusNode.hasFocus) {
      return _pinTheme.selectedColor;
    } else if (_selectedIndex > index) {
      return _pinTheme.activeColor;
    }
    return _pinTheme.inactiveColor;
  }
```

**Comment by adar2378** [comment]
When the pin code is completed (onCompleted will trigger), you can simply change the focus from the TextField, which will make all the cells green. The blue cell indicates that this is the selected cell, that means, if you type anything then that change will reflect on that cell. But when the TextField loses focus, which can be done by closing the keyboard, the blue mark will go away.

**Comment by nheumann** [comment]
Thank you for your hint. The pin input works as needed now. 👍
