### ISSUE TITLE
Bad state: Stream has already been listened to

### ISSUE THREAD

**Issue by RiteshChandnani** [adar2378/pin_code_fields#59]
Hi,
Thank you for creating the library, it is pretty good.

Just faced this issue - 
I have set a stream to `errorAnimationController`, the field itself is inside a stateful widget. I call setState and replace the field with a loader which causes the field's `dispose()` to be called but since the subscription to error stream is not cancelled, when the field is visible again it cannot listen to the same error stream.

afaiu, one possible solution could be to store the subscription returned by `listen` at https://github.com/adar2378/pin_code_fields/blob/master/lib/pin_code_fields.dart#L200
and cancel it in the dispose.

**Comment by adar2378** [comment]
Yes it can be better, for a quick solution you can use this:
`errorAnimationController = StreamController<ErrorAnimationType>.broadcast()`

**Comment by RiteshChandnani** [comment]
Was going in loop when I did that. For now, switched to stack and using opacity as suggested in #40.  
That worked.
