### ISSUE TITLE
Force typing direction to LTR

### ISSUE THREAD

**Issue by omidraha** [adar2378/pin_code_fields#68]
Hi,

Currently direction of typing in this widget is based on  current active local configuration of app.
But I would like to  force this widget to set direction of typing always to `LTR`.
Because in `Persian` language that is  `RTL` , but  typing `pin` doesn't make sense to type form right to left.

How to do that?
Or where is related lines of code for that.
I think it's related to this [code](https://github.com/adar2378/pin_code_fields/blob/4a7085ab195e2bba7865342a07bcd7f22f4e845f/lib/pin_code_fields.dart#L496), but i don't know which parameters can do it.

Thanks.

**Comment by adar2378** [comment]
Hi, I can't test it right now, but
`child: Row(
                  mainAxisAlignment: widget.mainAxisAlignment,
                  children: _generateFields(),
                ),
`
Here you can use https://api.flutter.dev/flutter/widgets/Directionality-class.html this widget and set the text direction to RTL. This can solve the issue I think

**Comment by omidraha** [comment]
Fixed as you said:

```dart
Directionality(
	  textDirection: TextDirection.ltr,
	  child: PinCodeTextField(...),
	  ),
```
Thanks a lot.
