### ISSUE TITLE
To be able to change keyboard Type

### ISSUE THREAD

**Issue by asarkar1990** [adar2378/pin_code_fields#69]
Please make it be able to change keyboard type to numeric only

**Comment by adar2378** [comment]
You can use this parameter to do so:
```
final TextInputType textInputType;
```

**Comment by nouveau-riche** [comment]
use this line inside your TextField or TextFormField Widget to change your keyboard to numeric

 keyboardType: TextInputType.number,

**Comment by adar2378** [comment]
Actually,
