### ISSUE TITLE
Not support iOS autofill

### ISSUE THREAD

**Issue by glennWang** [adar2378/pin_code_fields#7]
As the title say.

In my using scene，when iPhone get sms code，the code will be dissplayed on keyboard.

After clicking the sms code on keyboard, the code will  autofill the pin code.

However ,  pin_code_fields only fill the last pin code position with the other positions  empty.

The following two images cut from your example.

------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/7918942/68578155-6c889d80-04ac-11ea-8ca7-f6eda625e619.png)

![image](https://user-images.githubusercontent.com/7918942/68578194-80340400-04ac-11ea-8df5-c412d8a560e8.png)

**Comment by adar2378** [comment]
I'll surely check it out and see if I can add this feature. Thanks.

**Comment by adar2378** [comment]
Hi @glennWang , I don't have a real iPhone to send sms and test the autofill feature. Could you please clone this branch and use it then give me feedback about the autofill working or not? 
https://github.com/adar2378/pin_code_fields/tree/autofilltest

**Comment by glennWang** [comment]
The autofill feature is ok.   

And, there is still an another problem.  An absolute directory is used in your example. 

Just seeing the follow diff.


diff --git a/example/pubspec.yaml b/example/pubspec.yaml
index c837019..9f2cae6 100644

```
--- a/example/pubspec.yaml
+++ b/example/pubspec.yaml
@@ -24,7 +24,7 @@ dependencies:
   # Use with the CupertinoIcons class for iOS style icons.
   cupertino_icons: ^0.1.2
   pin_code_fields:
-    path: /Users/adar/Development/Flutter_workspace/pin_code/pin_code_fields
+    path: ../
   # change the path later
 dev_dependencies:
   flutter_test:
```

**Comment by adar2378** [comment]
oh yeah. Thanks. Do you think I should push this update?

**Comment by glennWang** [comment]
Yes,  I can not more agree with you.  😀😀😀

Thanks for your timely response.

**Comment by adar2378** [comment]
Updated the package 🎈😃

**Comment by softmarshmallow** [comment]
Why didn't this resolve #37 ?
Myself cannot make it work also.
