### ISSUE TITLE
"IF YOU WANT TO USE COLOR FILL FOR EACH CELL THEN SET enableActiveFill = true"

### ISSUE THREAD

**Issue by xJon** [adar2378/pin_code_fields#70]
I keep getting this message in my app's console after installing this package:
```
I/flutter (10411): IF YOU WANT TO USE COLOR FILL FOR EACH CELL THEN SET enableActiveFill = true
```
Is this intentional? Can I suppress it somehow?
Thank you!

**Comment by adar2378** [comment]
It's only for debug mode. During release mode, it won't be shown. Still, if you want to disable it in debug mode, 
Then go to line 177 of pin_code_fields.dart and remove that print statement or comment it out.
```
@override
  void initState() {
    if (!kReleaseMode) {
      print(
          "IF YOU WANT TO USE COLOR FILL FOR EACH CELL THEN SET enableActiveFill = true");
    }
```

**Comment by APDos** [comment]
Devs, you should really make this more apparent in the instructions for the package. I  was getting really frustrated trying to change the colors of the fields, which is a pretty important aspect, and I finally came across this. Love the work you've done!!

**Comment by erabti** [comment]
I think this should only be mentioned in the docs, this pollutes the logs in development and adds noise

**Comment by hampsterx** [comment]
```
if (!kReleaseMode) {
      print(
          "IF YOU WANT TO USE COLOR FILL FOR EACH CELL THEN SET enableActiveFill = true");
    }
```

why is this shown regardless of whether `enableActiveFill = true` ?
