### ISSUE TITLE
Add margin / padding between Pin View

### ISSUE THREAD

**Issue by kndl22** [adar2378/pin_code_fields#74]
Is it possible to add margin or padding when using PinCodeTextField?

I set my mainAxisAlignment to MainAxisAlignment.start and I want to put some space between the Pin Views..
Is it possible?

**Comment by adar2378** [comment]
Sorry, there is no attribute like that here, you can set a height and width for each cell, and the text will be shown in the middle. Suppose your font-size is 20, and you want to add 8 paddings, then make the cell's height 8+20+8 = 36, and width also 36. This is the same as writing ` EdgeInsets.all(8)`

**Comment by adar2378** [comment]
and for adding padding between each cells, you can get the total width of the screen, and then if you want to have 8 pixel gap between each cells then write a function to determine what should be the width of each cells.

```Dart
double getEachCellsWidth(){
    double totalWidth = // get total width using mediaquery
    double totalWidthAfterPadding = // If we have 4 cells with 8 padding between them then there will be 3 gaps where the //padding will be applied, hence it will be totalWidth - ((totalcells - 1) * 8);
    return totalWidthAfterPadding / totalcells;
}
```

Then set this value as your cell's width. Sorry that it's a bit extra work and all. But at least solves your problem.

**Comment by adar2378** [comment]
I'm closing this, feel free to comment further

**Comment by huynguyennovem** [comment]
@adar2378 : can you support to add margin between PinView? I think it's so easy to do that. Just wrap outside a Container with margin.

**Comment by juskek** [comment]
Would be great if there was a way to customise the spacing/padding between each field without having to change the width of each cell. Great package nonetheless!
