### ISSUE TITLE
Error occurs when increasing length with setState.

### ISSUE THREAD

**Issue by minikupa** [adar2378/pin_code_fields#75]
```
import 'package:flutter/material.dart';
import 'package:pin_code_fields/pin_code_fields.dart';

class testPage extends StatefulWidget {
  @override
  _testPageState createState() => _testPageState();
}

class _testPageState extends State<testPage> {

  int length = 4;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: <Widget>[
          PinCodeTextField(
            length: length,
          ),
          FlatButton(
            child: Text("addLength"),
            onPressed: () => setState(() => length++),
          )
        ],
      ),
    );
  }
}
```

Error occurs when increasing length with setState.

RangeError (index): Invalid value: Not in range 0..3, inclusive: 4

The relevant error-causing widget was: 
  PinCodeTextField lib/ui/pages/d.dart:18:11
When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/array.dart:16:52)
#1      _PinCodeTextFieldState._generateFields (package:pin_code_fields/src/pin_code_fields.dart:545:33)
#2      _PinCodeTextFieldState.build (package:pin_code_fields/src/pin_code_fields.dart:475:29)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)

**Comment by adar2378** [comment]
Yes, the length is fixed for now. Because changing it has a lot of side effects(setting text values, setting the colors of each field depending on acti). Could you please explain in what situation you need to change the length?

**Comment by minikupa** [comment]
I'm going to use this for a quiz app.(dynamic answer length)

**Comment by adar2378** [comment]
Cool. I am not sure if I can do this right now, kind of busy. You can fork it if you want. You will have manually re-initialize(call most of the functions inside initState) the process on length change.
