### ISSUE TITLE
Not able to type anything in the fields on web

### ISSUE THREAD

**Issue by imabhishekkumar** [adar2378/pin_code_fields#81]

**Comment by adar2378** [comment]
Could you share more details about it? Code snippets and flutter version information.

**Comment by imabhishekkumar** [comment]
Flutter version - `1.20.0-8.0.pre75`
This is the code I'm using -
`Container(
            width: 220.0,
            margin: EdgeInsets.only(top: 10.0),
            child: PinCodeTextField(
              length: 6,
              obsecureText: false,
              animationType: AnimationType.fade,
              backgroundColor: Colors.transparent,
              textInputType: TextInputType.number,
              pinTheme: PinTheme(
                shape: PinCodeFieldShape.box,
                borderRadius: BorderRadius.circular(5),
                fieldHeight: 30,
                fieldWidth: 30,
                inactiveColor: Theme.of(context).primaryColor,
                activeFillColor: Colors.black,
              ),
              textStyle: TextStyle(
                  color: Colors.black,
                  fontSize: 16.0,
                  fontWeight: FontWeight.bold),
              onChanged: (value) {
                currentText = value;
              },
            ),
          ),`

**Comment by softmarshmallow** [comment]
yeah wont work on chrome windows. works fine on mac chrome,

wont work on chrome windows, chroem andorid
