### ISSUE TITLE
HOWTO: create onTap callback of Field

### ISSUE THREAD

**Issue by Frezyx** [adar2378/pin_code_fields#84]
Hi, thank you so much for this package :blush: !
I have a problem using it. I can't find a method for getting an **onTap** callback.
How can I solve this problem ?

**Comment by adar2378** [comment]
Hey thanks! <3 
And you can wrap it with a gesture detector widget. Will that help?

**Comment by Frezyx** [comment]
![on_tap_problem](https://user-images.githubusercontent.com/40857927/89259549-34754c00-d633-11ea-9747-ea4eb423f390.gif)

I tried using gesture detector, but it catches only outside of the form and ignores the form itself. 
I made a fork of your package and made very small changes that solve this problem. 
Can I send these changes for review ?

**Comment by adar2378** [comment]
yes, that would be great. Please create a pull request
