### ISSUE TITLE
support  inputFormatters  and  onComplete(String val)

### ISSUE THREAD

**Issue by glennWang** [adar2378/pin_code_fields#9]
I have two ideas.

1. TextFormField  support keyboard inputFormatters such as : 
   `inputFormatters: [WhitelistingTextInputFormatter.digitsOnly]`
    
   Hope this config can be expose to developers.

2.  If  all pin code position has been filled ,  trigger a callback function like onComplete(String val) will be 
     better.

**Comment by adar2378** [comment]
Good idea :) I'll add them too! Thank you.
