### ISSUE TITLE
No option to set keyboard as only number

### ISSUE THREAD

**Issue by Dheena32** [adar2378/pin_code_fields#91]
Looking for an option to set number keyboard and inputAction

keyboardType: TextInputType.number,
textInputAction: TextInputAction.Nex....,

**Comment by adar2378** [comment]
Use this param:
`final TextInputType textInputType;`

**Comment by adar2378** [comment]
For action: 
`final TextInputAction textInputAction;`

**Comment by Dheena32** [comment]
Sorry i am not getting. Could you give a example
here my code
`PinCodeTextField(
                                      length: 6,
                                      obsecureText: false,
                                      animationType: AnimationType.fade,
                                      validator: (v) {
                                        if (v.length < 3) {
                                          errorController.add(
                                              ErrorAnimationType.shake);
                                          return "I'm from validator";
                                        } else {
                                          return null;
                                        }
                                      },
                                      pinTheme: PinTheme(
                                          //selectedColor: Colors.black,
                                          //activeColor: Colors.black,
                                          inactiveColor: const Color(0xFFF18722),
                                          //selectedFillColor: Colors.white,
                                          //inactiveFillColor: Colors.white,`

**Comment by Dheena32** [comment]
Sorry i am not getting. Could you give a example
here my code
`PinCodeTextField(
                                      length: 6,
                                      obsecureText: false,
                                      animationType: AnimationType.fade,
                                      validator: (v) {
                                        if (v.length < 3) {
                                          errorController.add(
                                              ErrorAnimationType.shake);
                                          return "I'm from validator";
                                        } else {
                                          return null;
                                        }
                                      },
                                      pinTheme: PinTheme(
                                          //selectedColor: Colors.black,
                                          //activeColor: Colors.black,
                                          inactiveColor: const Color(0xFFF18722),
                                          //selectedFillColor: Colors.white,
                                          //inactiveFillColor: Colors.white,`

**Comment by adar2378** [comment]
```Dart
PinCodeTextField(
   textInputAction: // here put the inputaction,
   textInputType: TextInputType.number,
/// other values
)
```
