### ISSUE TITLE
ReOpen keyboard

### ISSUE THREAD

**Issue by YaroslavGS** [adar2378/pin_code_fields#92]
Hello, I found a problem: if our textfield is in focus and we click on the field for entering the pincode again, the keyboard will reopen. I think this is not very good behavior and in this case the keyboard should remain open and not reopened. I tried to fix it myself, but then I ran into a problem when we close the keyboard with the system pop, then it stops opening altogether, since the focus of the node remains in focus. And processing through WidgetsBindingObservers and didChangeMetrics & MediaQuery.of (context) .viewInsets.bottom did not lead to any positive results.

**Comment by YaroslavGS** [comment]
Well, I fixed this problem ... by adding _onFocus to the callback
checking for the current keyboard height
if (MediaQuery.of (context) .viewInsets.bottom == 0) {
_focusNode.unfocus;
}
earlier there was a problem with the fact that the keyboard was called with a different context and, accordingly, in the context of the widget itself, it was not possible to correctly handle this situation.
Therefore, I propose to add an additional parameter to the constructor to the BuildContext widget so that the user can pass it in and the focusnode is called with the correct context. It may also fix other potential problems in the future.

**Comment by adar2378** [comment]
Hey Thanks for figuring this out!!! It would be lovely if you could create a pull request with your solution!

**Comment by adar2378** [comment]
Hey I've used your logic and fixed the issue in the new update :) Thanks for the suggestion.

**Comment by aggeloskoutanis** [comment]
I am still getting this problem in the latest version
