### ISSUE TITLE
Not responding to taps when I choose to autofill from SMS

### ISSUE THREAD

**Issue by subzero911** [adar2378/pin_code_fields#98]
My Android offers me to "automatically put codes from SMS".
If I agree, your pin code widget completely stops responding to manual input. I tap on it, and keyboard doesn't appear. Seems like it endlessly waits for SMS, blocking the input.
If I press the "back" button, a pin form begins working again.
The issue appeared only on the real device.

**Comment by adar2378** [comment]
ohho :( Sadly I don't have a real device to test it. Could you please try to see if there are any errors? Looks like the widget is not rebuilding maybe. When you press back it rebuilds and works again.

**Comment by darkang3lz92** [comment]
Seems like it's the autofill behaviour from Flutter, the same happen with normal TextField/TextFormField for AutofillHints.oneTimeCode.

**Comment by darkang3lz92** [comment]
https://github.com/flutter/flutter/issues/65144

**Comment by subzero911** [comment]
> Could you please try to see if there are any errors?

No, there's no errors in console
![image](https://user-images.githubusercontent.com/12999702/92535315-9aab4b00-f23f-11ea-8b01-1b5783df8247.png)

**Comment by subzero911** [comment]
Is it possible to turn off 'autofill from SMS'? This can break the UX, when user will tap to this option and think that an app is hang.
I don't need this functionality, I will fill the field with the pin code send to my email.

There's a new related API: https://medium.com/flutter-community/level-up-your-flutter-apps-with-autofill-1418a02db2e0
`autofillHints: [...]`
But I don't see these options in your plugin.

**Comment by darkang3lz92** [comment]
@adar2378 added a PR for disable autofill option #102

**Comment by subzero911** [comment]
Seems like it is fixed in Android.
![image](https://user-images.githubusercontent.com/12999702/102256863-fd863f80-3f1c-11eb-8bec-fc1c2e92c38a.png)
Such a "Waiting for message" bar began appearing.

**Comment by darkang3lz92** [comment]
Saw the fix as well. I believe we can close this issue now.
