### ISSUE TITLE
Add a keyboard type for the pins

### ISSUE THREAD

**Issue by slim-crown** [adar2378/pin_code_fields#99]
I didn't find any constructor to set my keyboard type to a numbers only keyboard. Can you please add that like regular textfields `Textfield(keyboardType: TextInputType.number) `**keyboard types** like https://api.flutter.dev/flutter/services/TextInputType-class.html

**Comment by adar2378** [comment]
To change the keyboard type, for example to use only number keyboard, or only for email use textInputType parameter, default is [TextInputType.visiblePassword]

**Comment by slim-crown** [comment]
ohhh okay thanks for that!

**Comment by adar2378** [comment]
Sorry, I should have named it as it is in the TextField widget, it's a bit confusing :(

**Comment by slim-crown** [comment]
Okay. Can you refactor it?

**Comment by adar2378** [comment]
Yes I plant to but so busy that can't work on this project right now :(
